### PR TITLE
use progress_bar option in detect_scenes

### PR DESCRIPTION
**Pull request by kianxineki**

### CODE REVIEW

**Comment by Gloin1313** [comment]
Hi @kianxineki!
Thanks for you contribution! We appear to be having a problem with the test suite at the moment, so we can't verify that your contribution works as expected. 

Would you like to create a test for this PR that demonstrates the usage of `progress_bar` in `detect_scenes`? Edit the file `tests/test_PR` to do that.

**Comment by mbeacom** [comment]
@kianxineki Additionally, can you rebase this with master?

Thank you for the contribution!

**Comment by stonebig** [comment]
merging soon ?

**Comment by scherroman** [comment]
Should close this, was already fixed in #587.

**Pull request closed without merging**
