### PR TITLE
Added option to export with alpha channel

### PR DESCRIPTION
**Pull request by jonata**
This add the option to export with alpha channel, may solve #559

### CODE REVIEW

**Comment by Zulko** [comment]
There is a syntax error in your commit. Did you try it on your machine ?

**Comment by jonata** [comment]
Sorry about this.

**Comment by Zulko** [comment]
thanks for the pull request. Can you replace "withmask" by "with_mask" ?

Also, do you have by chance some (non-copyrighted) bit of masked video (just a few seconds) that we could try this on (and write a test for the test suite) ?

Ideally the story of a test would be (1) load the video in moviepy with VideoFileClip, (2) write the video to another file, with the mask, (3) load the video from the new file and check that it still has a mask.

**Comment by jonata** [comment]
[moviepy_video_alpha_export.zip](https://github.com/Zulko/moviepy/files/1515753/moviepy_video_alpha_export.zip)

**Comment by darknoon** [comment]
Hey @jonata , thanks for your PR, using it locally I was able to export a clip with 4444 for integrating machine learning in python into a post workflow. It would be great to get this merged into master… need someone to clean it up?

**Comment by jonata** [comment]
Hi @darknoon , sorry my lack of experience, what I am supposed to do now?

**Comment by tburrows13** [comment]
Linking #1122.

**Comment by mondeja** [comment]
This has been fixed in #1237.

**Pull request closed without merging**
