### PR TITLE
Update code on README.rst

### PR DESCRIPTION
**Pull request by laurenL1202**
`with_position` and `with_duration` are now renamed to `set_position` and `set_duration`

### CODE REVIEW

**Comment by keikoro** [comment]
@laurenL1202 I'm not sure how you arrived at this conclusion, but the methods were actually renamed the other way round, see #1170. If you search the repo for the examples you gave, you'll notice GitHub doesn't return any results for code for `set_position` or `set_duration`.

Though it looks like there are leftover instances of the old method name `set_pos`, e.g. in several of the examples. Those would need updating (incl. testing that the examples in questions actually still work overall, I suppose).

**Comment by laurenL1202** [comment]
@keikoro hi, I have been using moviepy on a project and the methods work using the old names (`set_position`, `set_duration`). Not sure if the version from pip is outdated (1.0.3).

**Comment by laurenL1202** [comment]
Nevermind, just saw that the code works on 2.0. Thanks!

**Comment by keikoro** [comment]
@laurenL1202 Yup, the code in the repo has moved quite a bit beyond what's currently still up on PyPI. This problem is currently being discussed in a different recent issue (The Future of MoviePy).

**Pull request closed without merging**
