### PR TITLE
Add ‘ignore’ for UTF8 decoding to avoid error on non-UTF8 characters

### PR DESCRIPTION
**Pull request by chrisapplegate**
- [x] If this is a bugfix, I have provided code that clearly demonstrates the problem and that works when used with this PR
- [ ] I have added a test to the test suite, if necessary
- [ ] I have properly documented new or changed features in the documention, or the docstrings
- [ ] I have properly documented unusual changes to the code in the comments around it
- [x] I have made note of any breaking/backwards incompatible changes

I encountered an issue using moviepy with a video that had been produced by a Spanish-speaking client. In the metadata of the video, the description of the video had a non-UTF8 character in it - the letter "í" of "vídeo" was encoded in some non-UTF8 encoding.

```
    Metadata:
      creation_time   : 2018-10-11T14:40:32.000000Z
      handler_name    : Gestor de contenido de vídeo Apple
```

This was causing line 262 of `moviepy/video/io/ffmpeg_reader.py`, the function `ffmpeg_parse_infos`, to bug out with a `UnicodeDecodeError`:

```'utf-8' codec can't decode byte 0x92 in position 1712: invalid start byte```

I am not overtly familiar with this code base but I don't think adding `ignore` causes the code to break in any meaningful way. The code is not parsing or relying on that `Metadata` field, and as the exception wasn't being caught or handled, I don't think there is an expected input for this function that was working, and now no longer works thanks to this change.

### CODE REVIEW

**Comment by vildric** [comment]
I have the same issue and waiting for this PR to be merged.

**Comment by vildric** [comment]
this fix raise an OSError for me : 
`Traceback (most recent call last):
  File "/vagrant/moviepy/video/io/ffmpeg_writer.py", line 134, in write_frame
    self.proc.stdin.write(img_array.tobytes())
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/vagrant/apps/videos/models.py", line 98, in update_taster
    clip.write_videofile(filename=self.video3.path, threads=4, progress_bar=False)
  File "<decorator-gen-51>", line 2, in write_videofile
  File "/vagrant/moviepy/decorators.py", line 54, in requires_duration
    return f(clip, *a, **k)
  File "<decorator-gen-50>", line 2, in write_videofile
  File "/vagrant/moviepy/decorators.py", line 137, in use_clip_fps_by_default
    return f(clip, *new_a, **new_kw)
  File "<decorator-gen-49>", line 2, in write_videofile
  File "/vagrant/moviepy/decorators.py", line 22, in convert_masks_to_RGB
    return f(clip, *a, **k)
  File "/vagrant/moviepy/video/VideoClip.py", line 327, in write_videofile
    progress_bar=progress_bar)
  File "/vagrant/moviepy/video/io/ffmpeg_writer.py", line 225, in ffmpeg_write_video
    writer.write_frame(frame)
  File "/vagrant/moviepy/video/io/ffmpeg_writer.py", line 178, in write_frame
    raise IOError(error)
OSError: [Errno 32] Broken pipe

MoviePy error: FFMPEG encountered the following error while writing file /vagrant/media/videos/video/tasters/81_5I1Zgx6.mp4:

 b''
`

**Comment by tburrows13** [comment]
@chrisapplegate would you be able to provide a video that causes this behaviour?

**Comment by mylyu** [comment]
I support this fix

**Comment by mylyu** [comment]
No problem for me using this fix.

**Comment by chrisapplegate** [comment]
> @chrisapplegate would you be able to provide a video that causes this behaviour?

I am afraid not - when I filed this PR I was contracting for a client and I am no longer working for them. In any case, the video was confidential. It would not be too hard for me to annotate a public-domain video with the same, if you like?

**Comment by believeinnovation** [comment]
Here is one. We have the same problem from our side with this video : https://www.dropbox.com/s/k41malnj0cod4zt/test-videoblocks-footage-of-a-crowd-partying-at-a-rock-concert-or-dj-party_srgs6suqzb__a3c1a2474db660108239cf12e44a8ca7__P360.mp4?dl=0
It results in this error :
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/moviepy/video/io/VideoFileClip.py", line 91, in __init__
    fps_source=fps_source)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/moviepy/video/io/ffmpeg_reader.py", line 33, in __init__
    fps_source)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/moviepy/video/io/ffmpeg_reader.py", line 262, in ffmpeg_parse_infos
    infos = proc.stderr.read().decode('utf8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xce in position 2013: invalid continuation byte

**Comment by tburrows13** [comment]
@believeinnovation, does it work if you update to v2.0.0.dev2? (Use `--pre`` with pip to access pre-release versions).

**Comment by believeinnovation** [comment]
Hello Tom,
Yes with 2.0.0.dev2 this video file works 👍🏼
Is there any change file for this new version ?

Laurent Taupin
Chief Creative Technology Officer - Believe Group
laurent@believedigital.com
www.believedigital.com
Phone : +33 1 53 09 34 00 ext. 205
Help us preserving the environment. Print this document only if necessary.
This e-mail and its content are private and confidential and should only be read by those to whom it is addressed.
If you are not the intended recipient, you are hereby notified that any dissemination, distribution, copying, reproduction, modification or publication of this communication is strictly prohibited. If you have received this transmission in error, please contact us immediately on : +33(0)153093400, delete the message from your computer and destroy any copies. Please note that the information contained herein shall additionally constitute Confidential Information for the purposes of any NDA between the recipient(s) and Believe.
________________________________
De : Tom Burrows <notifications@github.com>
Envoyé : Friday, October 9, 2020 2:09:17 AM
À : Zulko/moviepy <moviepy@noreply.github.com>
Cc : GITHUB-BLVINNO <GitHub@believeinnovation.com>; Mention <mention@noreply.github.com>
Objet : Re: [Zulko/moviepy] Add ‘ignore’ for UTF8 decoding to avoid error on non-UTF8 characters (#959)


@believeinnovation<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbelieveinnovation&data=02%7C01%7Claurent.taupin%40believedigital.com%7Cde05b73d4fb84e5f77b508d86be790eb%7Cecffe4455fa449d4a7d666085d4523b1%7C0%7C0%7C637377989605406181&sdata=yEzGbKlywF3GUpE0z7gEkjPitj%2BgTr3ef8CuMlhx1B8%3D&reserved=0>, does it work if you update to v2.0.0.dev2? (Use --pre with pip to access pre-release versions).

**Comment by tburrows13** [comment]
Sure: https://github.com/Zulko/moviepy/releases/tag/v2.0.0.dev2 or https://github.com/Zulko/moviepy/blob/master/CHANGELOG.md

**Comment by Loskir** [comment]
is this still not released? :(

**Comment by tburrows13** [comment]
You can install `v2.0.0.dev2` with pip via using the `--pre` flag :)

**Comment by liulijiexian** [comment]
> You can install `v2.0.0.dev2` with pip via using the `--pre` flag :)您可以通过使用 `--pre` 标志 :) 来安装 `v2.0.0.dev2` pip
Even if updated to `v2.0.0.dev2`


The following error still occurs：


`ffmpeg_reader.py`


Attempt to delete the `.decode("utf8", errors="ignore")`


new error occurs `UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa3 in position 241: invalid start byte`

python: `Python 3.8.8`。

**Pull request merged**
