### PR TITLE
adding six for compatibility with py2 in ImageClip

### LINKED ISSUE #417: error 'unicode' object has no attribute 'shape'
i found this error with the python 2

### PR DESCRIPTION
**Pull request by leonardoo**
this fix #417

### CODE REVIEW

**Comment by Gloin1313** [comment]
Is there a way to do this without adding another dependency? I don't think we want to add a whole required module just for one small fix.

**Comment by earney** [comment]
I agree.  I would like to keep the dependencies as minimal as possible.
There are howtos of how to write code that is py2 and py3 compatible.

**Comment by Zulko** [comment]
@Gloin @earney I would also agree with no more dependencies, but here is a good example where ``six`` is the most elegant solution.

Have a look at this stackoverflow thread over this problem. All solutions not using six are much longer and sometimes cryptic.

http://stackoverflow.com/questions/11301138/how-to-check-if-variable-is-string-with-python-2-and-3-compatibility

I've never used six before as I prefer to use compatibilioty recipes, but ``six`` is only 10kb zipped, and has been downloaded more than 100 million times, so we can trust it. As we advance towards python2 and 3 compatibility and without a test suite, it may save us lots of headaches.

**Comment by mbeacom** [comment]
@Zulko @earney @Gloin1313 Maybe we can consider a solution like the [requests package](https://github.com/kennethreitz/requests/blob/master/requests/compat.py)? I was trying to avoid merging too much before we get a base test suite in place.

**Comment by Zulko** [comment]
@mbeacom  Six is basically the same kind of file, but put behind a library, and with a test suite.
Got you with the merging, there is too much enthusiasm and too early, lets take the necessary time to make the library maintainable (test suite, rules, how-tos, etc.).

Are you working on a test suite now or do you want me to start one ?

**Comment by earney** [comment]
I agree with the merging..  we need to create a basic test suite.  And add extra tests as issues arise.    Now, we might be breaking something, when we fix something else.

**Comment by earney** [comment]
PR #121 seems to address some testing issues, and how to set it up with github, etc.

**Comment by earney** [comment]
this is an easy fix, and we don't need six to do it..
Here is the basic code to do it:

change:

if isinstance(img, str):
   img = imread(img)

to
# add from ..compat import PY3    at the top of the file
if PY3:
           if isinstance(img, str):
               img = imread(img)
        else:
           if isinstance(img, (str, unicode,)):
               img = imread(img)

**Comment by leonardoo** [comment]
this will be merge?

**Comment by earney** [comment]
@leonardoo   it seems we have a couple contributors that wants to add six, but we have a couple that do not, so for now, I think we are holding off, until we can figure out how to proceed.   Please keep your Pull Request, and we will let you know ASAP.

**Comment by Zulko** [comment]
I'll fix that one with a merge later on. In that particular instance, we check that the provided image is a filename and not a numpy array. So instead of checking if the image is a string/unicode/bytes... we can just check that it is not a numpy array (``not isinstance(img, np.ndarray)``), which works fine in Py2 and Py3.

**Comment by earney** [comment]
@zulko   I can working on adding the not isinstance(img, np.ndarray), if you are too busy to add it in the next few days.

**Comment by earney** [comment]
the issue resolved in this PR is also fixed in PR #438

**Comment by earney** [comment]
PR #438 has been merged so this PR will not be used.  sorry..

**Pull request closed without merging**
