### PR TITLE
Added current and more general examples/headblur.py

### PR DESCRIPTION
**Pull request by berndf**
- [ ] If this is a bugfix, I have provided code that clearly demonstrates the problem and that works when used with this PR
- [ ] I have added a test to the test suite, if necessary
- [ ] I have properly documented new or changed features in the documention, or the docstrings
- [ ] I have properly documented unusual changes to the code in the comments around it
- [ ] I have made note of any breaking/backwards incompatible changes

### CODE REVIEW

**Comment by berndf** [comment]
This addresses https://github.com/Zulko/moviepy/issues/850

**Comment by tburrows13** [comment]
Probably also closes #167

**Comment by LaoYuanPython** [comment]
I had found the error is numpy's error,and has resolved!

**Comment by LaoYuanPython** [comment]
I had resolved this question,the detail is listed in :https://blog.csdn.net/LaoYuanPython/article/details/107307239。

**Comment by tburrows13** [comment]
@mondeja is there anything here that wasn't in #1414? Feel free to close if not

**Comment by mondeja** [comment]
It's deprecated due to `Trajectory` class missing, has failures, really obfuscated and unconsistent indentation. Sorry @berndf, I'm closing this. Feel free to open another pull request if you want to include functionalities not covered by #1414.

**Pull request closed without merging**
