### PR TITLE
Optimized character encoding detection

### PR DESCRIPTION
**Pull request by Lihao2017-11-15**
There was an error in the Chinese version of windows before.

### CODE REVIEW

**Comment by mondeja** [comment]
Please, could you share a minimal reproducible error?

**Comment by keikoro** [comment]
Ping, @Lihao2017-11-15

**Comment by keikoro** [comment]
@Lihao2017-11-15 Letting you know we've updated our CI settings. If you could update your PR to incorporate the latest changes to the code base – rebase master, (force) push the branch you used to open this PR – that'd be great.

**Comment by OsaAjani** [comment]
Thank you for your contributions and for reporting issues in this repository. With the release of v2, which introduces significant changes to the codebase and API, we’ve reviewed the backlog of open PRs and issues. Due to the length of the backlog and the likelihood that many of these are either fixed or no longer applicable, we’ve made the decision to close all previous PRs and issues.

If you believe that any of these are still relevant to the current version or if you'd like to reopen a related discussion, please feel free to create a new issue or pull request, referencing the old one.

Thank you for your understanding and continued support!

**Pull request closed without merging**
