### PR TITLE
Add warning to README.rst

### PR DESCRIPTION
**Pull request by B3QL**
Hi folks,
since nothing much had happened from the beginning of 2023
in terms of finishing version 2.0 or building a team around the project.

I see no choice but to warn other developers to not depend on MoviePy.

### CODE REVIEW

**Comment by B3QL** [comment]
@keikoro can you take a look?

**Comment by keikoro** [comment]
> @keikoro can you take a look?

I wouldn't agree it's "not maintained" – I'm still labelling issues here. ^^ But agree that a warning makes sense.

Maybe you could change it to something that doesn't make it sound like it's **dead dead**, but lets users know that what's on PyPI is outdated and that the project is struggling with releasing a new version? Otherwise people will be confused why the repo wasn't also set to archived.

**Comment by B3QL** [comment]
Hey @keikoro, you're right. The message was crafted before the rebirth of the discussion. I'll reword it next week when I will return from holidays. Sorry for late response :)

**Comment by B3QL** [comment]
@keikoro I tried to make it more informative and less scary, let me know if it's OK :)

**Comment by B3QL** [comment]
@keikoro depending on https://github.com/Zulko/moviepy/issues/1874#issuecomment-1652724032 the PR might not be needed :) I would love to close it, but let's wait.

**Comment by B3QL** [comment]
Closing in favour of https://github.com/Zulko/moviepy/pull/2024

**Pull request closed without merging**
