### PR TITLE
Fix #1895 printing `File Not Found` on Windows

### LINKED ISSUE #1895: File Not Found printed on the console after fresh install of pre-release
The package works, I can run all functionality but it prints something strange.
After installing the pre-release verion using pip install moviepy --pre or upgrading using pip install moviepy --pre --upgrade and from a simple script:

```
from moviepy.editor import *


def main() -> int:
    VideoClip()
    return 0


if __name__ == "__main__":
    main()
```

My console prints: "File Not Found"

#### Expected Behavior
Not to print anything

#### Actual Behavior
Prints "File Not Found"

#### Steps to Reproduce the Problem

Install the pre-release version using pip
Run the script below:
```
from moviepy.editor import *


def main() -> int:
    VideoClip()
    return 0


if __name__ == "__main__":
    main()
```
Check the console

#### Specifications

  - Python Version: 3.11.1
  - Moviepy Version: v2.0.0.dev2
  - Platform Name: Windows
  - Platform Version: 10

### PR DESCRIPTION
**Pull request by kifuan**
- [x] I have provided code that clearly demonstrates the bug and that only works correctly when applying this fix
- [x] I have properly documented new or changed features in the documentation or in the docstrings
- [x] I have properly explained unusual or unexpected code in the comments around it

Fix #1895.

Stop using system commands and use `pathlib` to find the ImageMagick binary under `C:\Program Files\ImageMagick-*` instead.

### CODE REVIEW

**Comment by kifuan** [comment]
Several tests failed when installing dependencies for the same reason, likely caused by the version string.

image

As for the code reformatting, I think it should be fixed in another PR or somewhere else.

**Comment by keikoro** [comment]
@kifuan Thanks for your PR. The black check errors should be fixed now.

**Comment by mgaitan** [comment]
> As for the code reformatting, I think it should be fixed in another PR or somewhere else.

Fixed in #1943

**Comment by kifuan** [comment]
ping @mgaitan @keikoro

**Pull request closed without merging**
