### PR TITLE
Wrapped callbacks

### PR DESCRIPTION
**Pull request by flovilmart**

### CODE REVIEW

**Comment by flovilmart** [comment]
Like the #150 but this way with a callback_generator function wrapped around.

**Comment by Zulko** [comment]
Thanks. Sorry for being slow on making a decision, I'm still thinking. Tell me if there is a pressing need to have these changes for your projects.

**Comment by flovilmart** [comment]
Those changes are in production right now. I'm using my branch so no hurry on your side.




What are you thinking?

**Comment by mike-johnson-jr** [comment]
Why did you remove the iterchunk_callback and iterframe_callback functions? I cloned https://github.com/flovilmart/moviepy and I get errors, I believe related to the removals. I am trying to update a progress bar for users in a frontend GUI for uploading and processing videos and am having trouble understanding the code. I'll be back to read more later

**Pull request closed without merging**
