### PR TITLE
added video and audio bit rate

### PR DESCRIPTION
**Pull request by crazyxw**
- [ ] If this is a bugfix, I have provided code that clearly demonstrates the problem and that works when used with this PR
- [ ] I have added a test to the test suite, if necessary
- [x] I have properly documented new or changed features in the documention, or the docstrings
- [ ] I have properly documented unusual changes to the code in the comments around it
- [ ] I have made note of any breaking/backwards incompatible changes

### CODE REVIEW

**Comment by Overdrivr** [comment]
Thanks for your contribution, could you please add a test case for checking the fix works as expected ?

**Comment by crazyxw** [comment]
Tests always go wrong, I don't know how to solve them.

**Comment by Overdrivr** [comment]
I've had a look, it seems this is due not to your code but the website we're pulling ImageMagick from that keeps removing old binaries pretty quickly. I'll fix this in another branch with a more reliable solution, I'll let you know when it's done.

**Comment by Overdrivr** [comment]
@crazyxw The fix is in #936. Let's just let CI complete.

**Comment by Overdrivr** [comment]
@crazyxw Fix is merged. Could you please merge master onto your branch ? Tests should run properly now.

**Comment by crazyxw** [comment]
@Overdrivr Errors still exist.

**Comment by Overdrivr** [comment]
Thanks for the heads up, I'm working on it (#940). Keep you posted

**Comment by Overdrivr** [comment]
Actually, it's #941

**Comment by Overdrivr** [comment]
@crazyxw Should be good now, can you merge latest master into your branch ?

**Comment by crazyxw** [comment]
@Overdrivr ok,it's work.

**Pull request merged**
