### PR TITLE
Fix issue #782

### LINKED ISSUE #782: Mirror doesn't affect mask on ImageClip
Hi!
Both mirror_x and _y doesn't affect the mask on ImageClip.

### PR DESCRIPTION
**Pull request by jacobwhiteman17**
Closes #782

- [x] I have provided code that clearly demonstrates the bug and that only works correctly when applying this fix
- [x] I have added suitable tests demonstrating a fixed bug or new/changed feature to the test suite in `tests/`

### CODE REVIEW

**Comment by mondeja** [comment]
I suppose that your fix is fine, but you're trying to introduce a lot of other changes not related. Could you clean this pull request or open another?

**Comment by keikoro** [comment]
@jacobwhiteman17 @jlindo33 @JonathanFurtado @Victrollia The PR you submitted is confusing because it features changes by all of you – was this a group effort/group project? We'd (again) ask you to clean this up or resubmit as separate PRs. Otherwise, please close the PR or leave some sort of response, thanks.

**Comment by JonathanFurtado** [comment]
Hi, this PR was indeed a group project. We no longer need this PR to be
active, so if you'd like, you can go ahead and scrap the entire thing.

Thank you,
Jon

**Comment by keikoro** [comment]
Closing this as the submitters don't want to move forward with this.

**Pull request closed without merging**
