### PR TITLE
write_videofile preset choices doc

### PR DESCRIPTION
**Pull request by gcandal**
Current choices don't seem to be correct according to https://trac.ffmpeg.org/wiki/Encode/H.264#a2.Chooseapreset

### CODE REVIEW

**Review by mbeacom — COMMENTED** [review]
It seems you mistakenly removed a space in this commit.

**Comment by gcandal** [comment]
You were right ;)

**Comment by kerstin** [comment]
Is this a fix for #282?

**Comment by gcandal** [comment]
Yes 👍

**Review by mbeacom — APPROVED** [review]
:shipit:

**Pull request merged**
