### PR TITLE
fix bug with transparent background clips

### PR DESCRIPTION
**Pull request by Humper**
Fixes bug #227

### CODE REVIEW

**Comment by earney** [comment]
@Humper  can you give us an example where this fails before your PR?   I've tried a few examples and those examples work for me.

**Comment by earney** [comment]
@Humper    Here is the example I'm trying to use to duplicate your issue (#227) and verify your PR (#228).

```
green = ColorClip((800, 600), color=(0,255,0))
    green.mask = ColorClip((800,600), color=1.0, ismask=True)
    red = ColorClip((400, 300), color = (255,0,0), duration=1)
    blue = ColorClip((400, 300), color = (0,0,255), duration = 2)
    clip=CompositeVideoClip([green, blue, red], use_bgclip=True).set_duration(3)
    clip.write_videofile("/tmp/issue_227.mp4", fps=30)
```
This seems to work the same way before and after the PR.  What am I overlooking?  Can you fix my example, or can you supply one of your own?
Thanks!

**Comment by frazras** [comment]
Try using a Textclip in your example, that fails for me

**Comment by mondeja** [comment]
This was addressed [here](https://github.com/Zulko/moviepy/commit/fdc51d29b7ce2f3b2c4d0d907c1c62b5da168128).

**Pull request closed without merging**
