### PR TITLE
Fixed errors in docs

### PR DESCRIPTION
**Pull request by jonnekaunisto**
* Fixed a broken link in gallery
* Put code into a code block in quick_recipes

### CODE REVIEW

**Comment by tburrows13** [comment]
The Kapwing section was added in #509... @justswim, are you still using moviepy? Do you have a replacement for whatever used to be linked to in the docs?

**Comment by justswim** [comment]
Hi @tburrows13, sorry for the late reply. Yes, we still are using moviepy! 

Here is a replacement video link that you can use - will you be able to update this PR with it?
https://cdn.kapwing.com/video_5e681ac49187d40016ee123e_579130.mp4

Thanks,
Eric

**Comment by tburrows13** [comment]
Thanks for the PR, @jonnekaunisto! It's now been merged.

**Comment by videowala** [comment]
Hey @justswim, Kapwing looks awesome. How are you rendering videos so fast using MoviePy? Are you doing multithreading?

**Comment by sahils2410** [comment]
@tburrows13 @justswim it would be really helpful if you could answer @videowala :)

**Pull request merged**
