### PR TITLE
Fix audio cutout issue #1682

### PR DESCRIPTION
**Pull request by selentium**
- [x] I have provided code that clearly demonstrates the bug and that only works correctly when applying this fix
- [x] I have added suitable tests demonstrating a fixed bug or new/changed feature to the test suite in `tests/`
- [x] I have properly documented new or changed features in the documentation or in the docstrings
- [x] I have properly explained unusual or unexpected code in the comments around it

This PR provides fix for issue #1682

### CODE REVIEW

**Comment by keikoro** [comment]
@selentium Thanks for the update to the PR. If you check the Black results, you'll see which of your own code's formatting needs fixing now.

Btw. if you follow the instructions in the CONTRIBUTING file, you should end up with Black installed for development, meaning you'll be able to catch these errors before submitting your code.

**Comment by keikoro** [comment]
Btw. we've meanwhile updated our CI settings, so the next time you push changes, most of the failed checks should turn green, which may make things less confusing.

**Comment by keikoro** [comment]
@selentium Any update on this?

**Comment by selentium** [comment]
@keikoro  thanks for your help, think it will pass formatting checks now. However, I was testing workflows in my forked repo and it doesn't pass Windows tests. Checked it and it seems it's an error in workflow itself ( it fails at ImageMagic install ), not sure what's the correct way to handle it.

**Comment by keikoro** [comment]
@selentium I assume the paths to the Windows binaries were the problem – they got fixed today. Could you rebase the current master and push your changes again? This would make it possible to rerun the workflows.

**Comment by selentium** [comment]
Is there anything else I can do to help close this PR?

**Comment by OsaAjani** [comment]
Hey @selentium V've closed the PR because we are currently doing some cleaning and removing on old PR with the new V2 release. The bug this PR was fixing still exists though, and i think your PR fixed it and I would like to re-open it.
You would need to update your tests to use the code for the new v2 though (see https://zulko.github.io/moviepy/getting_started/updating_to_v2.html). It would also be nice to have a smaller rain.mp3 by simply cutting it to be about a minute long not more.

Would you be willing to do so, or should I simply copy the code changes from your PR and make my own ?

**Comment by OsaAjani** [comment]
Without response I'm closing this PR and rewriting it with the needed fixes for v2.

**Pull request closed without merging**
