### PR TITLE
pick highest fps when concatenating

### PR DESCRIPTION
**Pull request by BrianLee608**
These changes resolve issue [407](https://github.com/Zulko/moviepy/issues/407)

### CODE REVIEW

**Comment by Zulko** [comment]
This forgets the case where all the fps may be None (this happens if you are concatenating a series of still pictures), at which case the concatenation's fps should be None. Here you'll get a bug with the max. Can we add something like this ?
```
if all([clip.fps is None for clip in clips]):
    self.fps=None
```

**Comment by BrianLee608** [comment]
I think something went weird with my revised PR. 

But I just changed the logic to:
```
fpss = [c.fps for c in clips if hasattr(c,'fps')]
    if len(fpss) == 0:
        result.fps = None
    else:
        result.fps = max(fpss)
```

It avoids looping through the clips twice.

**Comment by earney** [comment]
can we commit this PR?  It passes the 4 or 5 tests, I have created so far.  I also have a test for this issue that needs to be uncommented once this PR is committed.    I'll commit it if no one objects by Wednesday March 1st.

**Comment by Zulko** [comment]
Sure go ahead. If it ever go causes trouble in some scenarios it will be easy to revert/refine later.

**Comment by Zulko** [comment]
Wait actually my remark above hasn't been fully addressed. The line should read like this to take into account that some clips have a fps equal to None:

```
fpss = [c.fps for c in clips if hasattr(c,'fps') and c.fps is not None]
```

**Pull request merged**
