### PR TITLE
fix issue #401

### PR DESCRIPTION
**Pull request by earney**
this fixes a python 3 error dealing with strings and bytes.   See issue #401 for more details of this error.

### CODE REVIEW

**Comment by Gloin1313** [comment]
This does the same as https://github.com/Zulko/moviepy/pull/295/files ?

**Comment by earney** [comment]
Gloin1313..    I didn't see  pull 295 before I created my version.  Sorry.   I like my solution better, but I'll let the maintainers to choose what version they like best. :)

**Comment by Gloin1313** [comment]
I'm not experienced so I can't comment which I like better. I'm not even sure the other one works on Python 2, but obviously it works fine with Python 3.

**Comment by earney** [comment]
Looking at this more closely, there is a difference..   
Line 85, will also through an error on python 3

   self.proc.stdin.write(frames_array.tostring())
(for python 3) needs to be
   self.proc.stdin.write(frames_array.tobytes())

**Comment by earney** [comment]
I tried my version on python 2 and python 3 and it seems to work.  At least
for the couple of test cases I used.

**Comment by Gloin1313** [comment]
The tobytes()/tostring() difference causes an imageio crash from somewhere else when I run moviepy until I fix it in the code. However, this difference makes no difference either way.

**Comment by earney** [comment]
that is funny.. I don't get the crash..

I'm running Ubuntu 16.10
My version of imageio  is 2.1.2   (for python 3 and for python 2).

What are your versions?

**Comment by earney** [comment]
@Zulko  @mbeacom   anyway of getting this merged in?
Thanks!
Billy

**Comment by mbeacom** [comment]
@earney Thanks for the contribution!  I prefer your approach to this. 
However, It appears this might be an issue in the [ffmpeg_audiowriter](https://github.com/Zulko/moviepy/blob/master/moviepy/audio/io/ffmpeg_audiowriter.py#L92) as well based on the issue #335 and the resolution presented in #295.

I believe this is the appropriate way to go and it resolves #401. We'll want to resolve #335 before pushing a release.

**Comment by earney** [comment]
Thanks. I will look into the fixing the other issue you mentioned


On Feb 14, 2017 5:53 PM, "Mark Beacom" <notifications@github.com> wrote:

*@mbeacom* approved this pull request.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Zulko/moviepy/pull/403#pullrequestreview-21895397>, or mute
the thread

**Comment by Gloin1313** [comment]
It should be extremely easy to add this to ffmpeg_audiowriter as well

**Comment by earney** [comment]
@mbeacom now, this pull also fixes issue #335. :)

**Pull request merged**
