### PR TITLE
Fix typo in docstring

### PR DESCRIPTION
**Pull request by ricqosu**
Fixed typo in doc string

### CODE REVIEW

**Comment by luzpaz** [comment]
Looks correct.

**Comment by keikoro** [comment]
While improving a docstring's _contents_, it'd be great to simultaneously also fix issues with its formatting, see [PEP 257](https://peps.python.org/pep-0257/#multi-line-docstrings).

**Comment by kishcs** [comment]
Looks fine. We can review and close minor PRs.

**Comment by keikoro** [comment]
@kishcs That's kind of a weird thing to say to an admin as a random user. The no. of mystery reviews on this non-essential PR by unrelated 3rd parties makes this increasingly look like an excercise to me. It's def. reminiscent of Hacktoberfest a few years back, when people put quantity of contributions over quality.

>  We can review and close minor PRs.

We can also learn from suggestions on how to improve the quality of our contributions, especially when that requires very little effort.

**Comment by kishcs** [comment]
Definitely. I was just telling to reduce the PR count and to narrow down the focus on real issues and PRs. In case it's no quality, you can reject it too. 🙏

**Comment by keikoro** [comment]
The chronology of actions taken on this PR and OP not showing interest in improving their submission is fascinating, in any case. Guess I wasn't too far off with what I said last.

**Pull request closed without merging**
