### PR TITLE
fix typo that introduces audio regression

### LINKED ISSUE #891: [0.2.4.0] Garbled audio when exporting mp3 from mp4?
### Expected Behavior
Audio extracted to mp3 should sound like in video

### Actual Behavior
Low volume and weird sounds.
Video: https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_30mb.mp4
Extracted audio: https://www.dropbox.com/s/czytk0pudmn4xj7/bad-audio.mp3?dl=1

### Steps to Reproduce the Problem

```python
with VideoFileClip('big_buck_bunny_720p_30mb.mp4') as clip:
   clip.audio.write_audiofile('out.mp3')
``` 

### Specifications

  - Python Version: 2.7.12
  - Moviepy Version: 0.2.4.0
  - Platform Name: Ubuntu
  - Platform Version: 18.04

### PR DESCRIPTION
**Pull request by chrox**
This should fix #891.

- [x] If this is a bugfix, I have provided code that clearly demonstrates the problem and that works when used with this PR
- [ ] I have added a test to the test suite, if necessary
- [ ] I have properly documented new or changed features in the documention, or the docstrings
- [ ] I have properly documented unusual changes to the code in the comments around it
- [ ] I have made note of any breaking/backwards incompatible changes

### CODE REVIEW

**Comment by Zulko** [comment]
Indeed ! Thank you very much.

**Comment by dannyshisler** [comment]
Please merge this, this issue has caused me a lot of problems today! Thanks

**Comment by Zulko** [comment]
Sorry. Merged now.

**Comment by dannyshisler** [comment]
Thanks a lot.

**Pull request merged**
