### PR TITLE
Add video option to AudioClip.write_audiofile()

### PR DESCRIPTION
**Pull request by thenewguy**
This exposes FFMPEG_AudioWriter's input_video kwarg which now allows AudioClip.write_audiofile() to specify the path to a video file that will be copied to the ffmpeg file output.

It is analogous to VideoClip.write_videofile() with the audio kwarg set as string.  Clip integration is not yet written but should be easily extendable if needed.  I currently do not need it so I did not implement.

### CODE REVIEW

**Comment by tburrows13** [comment]
This looks very interesting: thanks for making and submitting it. I think that the commits are getting overlapped with #1036. Maybe if you merge your branch for #1036 into this one then it will fix it?

**Comment by thenewguy** [comment]
@tburrows13 will do - glad you like it!  I am making sure that my branches merge together here: https://github.com/thenewguy/moviepy/tree/improvements-2019 to work with a local project.  If you like these three PR and it is easier on you, I am happy to submit a merged PR

**Comment by thenewguy** [comment]
@tburrows13 the auto codec selection in AudioClip.write_audiofile() is tripping me up.  Because I am testing writing audio into a video format that copies video.  So the audio codec selected is a video format.  What do you think about a new factory function for codec lookups that takes a "hint" of audio/video/image?

**Comment by thenewguy** [comment]
@tburrows13 Probably out of scope for this PR, but you can take automatic codec selection one step further by selecting the first codec that a particular ffmpeg build supports with something like:

```
        def assert_rendition_ffmpeg_encoder_installed(self, encoder):
            result = subprocess.run(
                [
                    imageio.plugins.ffmpeg.get_exe(),
                    "-h",
                    "encoder=%s" % encoder,
                ],
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                universal_newlines=True,
            )
            result.check_returncode()
            self.assertNotIn('is not recognized', result.stdout)
```

**Comment by thenewguy** [comment]
Closing in favor of #1039

**Pull request closed without merging**
