### PR TITLE
Revert "add afterimage example"

### PR DESCRIPTION
**Pull request by Zulko**
Sorry for reverting this one, but as it seems to add dependencies (to an external repo if I understand well, but there seems to be also a new module "download_media" which I don't understand), I'd prefer to give it some thoughts.

### CODE REVIEW

**Comment by earney** [comment]
most of the tests refer to the download_media module.  

I created the earney/moviepy_media repo, so that we can store media files for testing, but keep the zulko/moviepy repo small.

**Comment by Zulko** [comment]
Oh I didnt notice download_media is just a local file. Neverming, I think I just over-reacted.

**Comment by earney** [comment]
No worries..  :)   feel free to remerge this PR, when you feel comfortable..

**Comment by Zulko** [comment]
Not sure what you mean, your original PR is still merged, what I just closed is my Revert PR, or am i confused ?

**Comment by earney** [comment]
Sorry.. I was confused.  I see the file in the repo, so all is fine.

**Pull request closed without merging**
