### PR TITLE
Fix issue #464, repeated/skipped frames in ImageSequenceClip

### PR DESCRIPTION
**Pull request by neitzal**
This PR fixes the occasional repeating and skipping of frames mentioned in issue #464 due to floating point inaccuracies in images_starts.

### CODE REVIEW

**Comment by earney** [comment]
@neitzal, would it be possible for you to add a test for this that would fail before your fix, but succeeds after your fix?   You can post it here or you can add it to tests/test_issues if you want.  Is that okay?

**Comment by neitzal** [comment]
@earney Sure, I added a test for one failure case that now succeeds. The test is not exhaustive though, in the sense that it does not verify that no fps-number (in a reasonable range) ever produces a frame mismatch. I guess that would be a little too expensive to run every time.

**Comment by earney** [comment]
Awesome..  Thanks!

**Comment by earney** [comment]
@Zulko   do you think this would be okay to merge into the repo?  I'm not an expert on ImageSequenceClip so I'm a bit hesitant.

**Comment by earney** [comment]
scipy does not support python 3.3 anymore (but supports 2.7, 3.4, 3.5 and 3.6).  if we accept this PR we will lose python 3.3.  is that okay with everyone?

**Comment by earney** [comment]
any objections to this PR?

**Comment by Zulko** [comment]
LGTM

**Pull request merged**
