### PR TITLE
`Colorclip` changed `col`>`color`

### PR DESCRIPTION
**Pull request by Gloin1313**
Changed the `col` paramater of `ColorClip` to `color` and added a DeprecationWarning if the users tries to use `col`.

### CODE REVIEW

**Comment by kerstin** [comment]
Does this fix #366? Dropping the no. in here so this PR is linked from the issue.

**Comment by Gloin1313** [comment]
Sorry, yes, it does.

**Comment by earney** [comment]
Gloin1313.  this looks good to me.  Should we go ahead and merge?   Anyone object?

**Comment by Zulko** [comment]
Just two remarks: please enforce PEP8, no line with more than 80 characters, it's really important.
Also -less important- maybe in a first time we could raise a warning instead of an error, i don't really like to have a parameter there with no other purpose than throwing an error.

**Comment by earney** [comment]
@zulko..  is there a way we can add PEP 8 testing of the source code?  I've heard of this, but I haven't tried it myself.  Maybe one else has some experience with PEP 8 testing and github.

**Comment by Zulko** [comment]
[There are](https://pypi.python.org/pypi/pep8) but I've never been really confortable with these, in some cases you have to disregard PEP8 for one line or two, and that makes your tests fail. On moviepy you'll certainly have a lot of red flags. I'd suggest we just keep the basics of PEP8 in mind (line length, naming, etc.) and just eyeball one another's code.

**Comment by earney** [comment]
good points..  We don't want to get too anal about this.. ;)

**Comment by kerstin** [comment]
@earney @Gloin1313 Any decent code editor will allow you to use a word wrap column/ruler, which can be set to 78-80 characters (78 being preferred because of the extra spaces just in case).

It's not just useful if you want to follow PEP8, but also on sites like GitHub, where longer lines have to be scrolled horizontally, which is a pain. For the rest, a read-through of the [PEP8](https://www.python.org/dev/peps/pep-0008/) page as a refresher should suffice (+ maybe checking back with it a few times for those completely new to it).

**Comment by Gloin1313** [comment]
@Zulko I'll add those suggestions. Sorry about the line length thing, I'll make sure it doesn't happen again! When you say "warning", do you mean just `print("Moviepy WARNING: message here)` or do you mean something like [the standard library warnings module](https://docs.python.org/3/library/warnings.html#module-warnings)?
Whichever we do, I'll then add `color = col`, unless both are specified, in which case I'll use `color` and have another warning that `col` is being ignored.

**Comment by earney** [comment]
@Gloin1313 ,  we are using the warnings module in /moviepy/moviepy/video/io/ffmpeg_reader.py.  So that is probably what @Zulko  is referring to.
Can you also create a test or two for this PR and place it in  test/test_PR.py ?  Let me know if you need some help.

**Comment by Gloin1313** [comment]
This is ready to go. Is it OK if I place the test in a separate PR? The `colorclip-update` branch doesn't have the `test_PR.py` file as it was added since I created the branch.

**Comment by earney** [comment]
Sure..  we can merge the two files together later.

**Comment by Gloin1313** [comment]
@earney About the tests: are they just testing for proper usage, or shall I put one in using `col` to check the  warnings work ok as well?

**Comment by Gloin1313** [comment]
Tests are in this one after all. Ready to go

**Comment by earney** [comment]
Nice work..  unless someone objects, I'd merge this into the repo.  Maybe give others a few days to respond (maybe till friday?)

**Comment by Gloin1313** [comment]
There are a lot of commits in the PR. Is the right thing to do "rebase and merge" instead of just "Merge pull request"? Or do we "squash and merge"?

**Comment by earney** [comment]
A squash and merge will do what u want.

**Pull request merged**
