### PR TITLE
Adds iterframe_callback as per #128

### PR DESCRIPTION
**Pull request by flovilmart**

### CODE REVIEW

**Comment by Zulko** [comment]
Thanks for the commit. I'm still unsure how this should be implemented. In #128 @BAXTER001 proposed *a generator function to this method to be wrapped around the current generator()*, which is also a good idea. An objection I have in your implementation is that you propose iterframe_callback as a class methods, and in python 3 these can only be overwritten by creating a new subclass. I would prefer if it was just an attribute. But yet again, I'm not sure it shouldn't be a wrapper around range().

**Comment by flovilmart** [comment]
Ok. The thing is that I hacked it quickly as I needed to estimate the processing time for the rest of my pipeline.




I generally don't care much about the form of the solution, as long as it's effectively working.




Replace the tqdm generator with a custom progress would be a solution. But also I'm not sure this is what you 'want'.

**Comment by lrq3000** [comment]
Hey there, the [tqdm project is now maintained by another team of developpers](https://github.com/tqdm/tqdm) (which I am part of), and the version has been updated to v3.1.4 lately (but the API should be the same, this should not break anything from what I've seen by quickly skimming through moviepy code).

We have described in the readme an example of [how to do a wrapper/callback to tqdm](https://github.com/tqdm/tqdm#hooks-and-callbacks), without needing to modify tqdm's code.

If this is not enough, the project is also now modularized and object-oriented, so that you can overload the tqdm class to easily interface with your setup, like we did for [IPython](https://github.com/tqdm/tqdm/blob/ipython-notebook/tqdm/_tqdm_notebook.py) and [pandas](https://github.com/tqdm/tqdm/blob/master/tqdm/_tqdm_pandas.py). This allows to let tqdm do the ugly work (time prediction, skipping useless iterations to lower CPU usage, etc.), and just focus on interfacing with your app.

Feel free to come and ask us if you cannot sort this out, we can maybe help you achieve what you want (and make tqdm better by the way).

**Comment by flovilmart** [comment]
the PR was in response to #128 and I actually needed that for a project. As this branch is stable, it will still be in use in the project and we'll see in the future if we need to update.

Thanks.

F.

**Comment by lrq3000** [comment]
Ok :) Feel free to come talk with us if you have a specific need, we try to make tqdm more and more flexible without compromising on the performances ;)

**Comment by mbeacom** [comment]
@flovilmart Thank you for the contribution!

Would you like to rebase this for further review or would you prefer to close the PR?

Thanks

**Comment by flovilmart** [comment]
I don't use the project anymore, but I could give it a shot if it's something you want in main codebase.

**Comment by jameshhx** [comment]
One note I'll make on this is that when using the `CompositeAudioClip`, this will throw an error due to `iterchunk_callback` being undefined. This is due to the fact `CompositeAudioClip` calls `__init__` on `Clip`, instead of the class it's extending `AudioClip`. I've fixed this issue locally by changing where `CompositeAudioClip` calls to `__init__`. This feature is something that I'd find useful - is it something you'd be willing to consider merged, if I can get it to a complete state?

**Comment by flovilmart** [comment]
Closing as I'm not using the project anymore. Feel free to pick it up!

**Comment by Zulko** [comment]
Oh yeah sorry for that and thanks for the past efforts. The project now uses [Proglog](https://github.com/Edinburgh-Genome-Foundry/Proglog) loggers for logging, which makes it possible to have custom callbacks, redirect logs to a frontend, etc. by configuring the Proglog loggers.

**Comment by flovilmart** [comment]
No problem! Thanks you for still maintaining itb

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Pull request closed without merging**
