### PR TITLE
Use popen.communicate() to prevent subprocess hang

### PR DESCRIPTION
**Pull request by tehKost**
Broken video files caused ffmpeg subprocess to hang

### CODE REVIEW

**Comment by mgaitan** [comment]
could we merge this?

**Comment by tburrows13** [comment]
It looks like this has already mostly been implemented elsewhere, however without the `terminate()`.

**Comment by tburrows13** [comment]
It looks like this has already mostly been implemented elsewhere, however without the `terminate()`.

**Comment by tburrows13** [comment]
Largely superseded by #926, but I'm going to merge this change which now adds `proc.terminate()`. I doubt that it is necessary, but I don't think that it can hurt.

**Pull request merged**
