### PR TITLE
imageio.core.fetching.NeedDownloadError: Need ffmpeg exe. 

### PR DESCRIPTION
**Pull request by Titashdas**
ERROR:  imageio.core.fetching.NeedDownloadError: Need ffmpeg exe.
I face the abovementioned error while running test_examples.py.
I think we should add this two line of code in the program so that user don't face this error
```
import imageio
imageio.plugins.ffmpeg.download()
```

### CODE REVIEW

**Comment by Gloin1313** [comment]
This PR seems rather large... I'm assuming that you've only actually changed a few lines though...?

**Comment by Titashdas** [comment]
Yeah i want to add abovementioned 2 lines only.

**Comment by mbeacom** [comment]
Should this PR be targeting `gh-pages` branch?

**Comment by mbeacom** [comment]
This pull request is based on our `master` branch merging into `gh-pages`. You will need to fork the repository, create a separate branch, make your changes, and submit a PR from there.

Let us know if you have any questions!

**Pull request closed without merging**
