### PR TITLE
Add progress_bar option to write_images_sequence

### PR DESCRIPTION
**Pull request by achalddave**

### CODE REVIEW

**Comment by Gloin1313** [comment]
I'll test this, and merge if successful

**Comment by mbeacom** [comment]
@Gloin1313 Do you think this is good to go for the next release?

**Comment by Gloin1313** [comment]
Sorry, I still haven't tested it yet... I will get round to it.

**Comment by Gloin1313** [comment]
This does what is says. When using `write_images_sequence`, setting the parameter `fps` to anything other than `1`, the progress bar behaved a little weirdly, but that was nothing to do with this PR.

**Comment by Gloin1313** [comment]
Oops, sorry. Just realised I had closed this, not merged it!

**Pull request merged**
