### PR TITLE
Fix no audio in output videos

### PR DESCRIPTION
**Pull request by Baronsindo**
i removed '-an'
because of it the outputted videos has no sound

- [X] If this is a bugfix, I have provided code that clearly demonstrates the problem and that works when used with this PR
- [ ] I have added a test to the test suite, if necessary
- [ ] I have properly documented new or changed features in the documention, or the docstrings
- [ ] I have properly documented unusual changes to the code in the comments around it
- [ ] I have made note of any breaking/backwards incompatible changes

### CODE REVIEW

**Comment by Overdrivr** [comment]
Thanks for your contribution, does this PR refers to #876 ?
Could you write a test case demonstration the lack of audio in the exported file ?

**Comment by ThePhonon** [comment]
Note: the -an option is arguably needed.  The bug is that it is provided before the '-i' option.
See https://github.com/Zulko/moviepy/pull/968

**Comment by Baronsindo** [comment]
Thanks for clearing that out.

**Comment by tburrows13** [comment]
The general census seems to be that #968 should be merged, not this one.

**Pull request closed without merging**
