### PR TITLE
fix slideout func

### PR DESCRIPTION
**Pull request by jakeywu**
- [ ] If this is a bugfix, I have provided code that clearly demonstrates the problem and that works when used with this PR
- [ ] I have added a test to the test suite, if necessary
- [ ] I have properly documented new or changed features in the documention, or the docstrings
- [ ] I have properly documented unusual changes to the code in the comments around it
- [ ] I have made note of any breaking/backwards incompatible changes

### CODE REVIEW

**Comment by Overdrivr** [comment]
Thanks for the contribution, could you please:
- point to which ticket this fix is referring ?
- add a test case showing this fix works as expected ?

Thanks

**Comment by changlehu** [comment]
slide_out function is still wrong :

    pos_dict = {'left': lambda t: (min(0, w*(1-(t-ts)/duration)), 'center'),
                'right': lambda t: (max(0, w*((t-ts)/duration-1)), 'center'),
                'top': lambda t: ('center', min(0, h*(1-(t-ts)/duration))),
'bottom': lambda t: ('center', max(0, h*((t-ts)/duration-1)))}

should be:

    pos_dict = {'left': lambda t: (min(0, w*(0-(t-ts)/duration)), 'center'),
                'right': lambda t: (max(0, w*((t-ts)/duration-0)), 'center'),
                'top': lambda t: ('center', min(0, h*(0-(t-ts)/duration))),
'bottom': lambda t: ('center', max(0, h*((t-ts)/duration-0)))}

All number "1" should be corectted to number "0". Now it works fine.

**Comment by tburrows13** [comment]
Duplicate of #795. Its worth changing the docstring as well, seeing as `concatenate` is deprecated. #795 makes some further changes that should be considered. @changlehu your suggestions are functionally identical to this PR anyway, I think. Your `0-(t-ts)` is the same as `(ts-t)` suggested by this PR and `-(t-ts)` suggested by #795.

**Comment by tburrows13** [comment]
Closing in favour of #795.

**Pull request closed without merging**
