### PR TITLE
Correcting text

### PR DESCRIPTION
**Pull request by gpantelis**
Change the 'au' to 'and'

### CODE REVIEW

**Comment by Zulko** [comment]
thanks !

**Comment by gpantelis** [comment]
What coverage represents? sorry for this question.

**Comment by kerstin** [comment]
@gpantelis I asked basically the same question in #509, so will redirect you to there.

I *think* it tests for actual testing, so new contents/lines that are not covered by tests (which documentation and doc fixes etc. naturally aren't) will always decrease the existing "coverage" ("are these lines of code/stuff covered by tests?").

**Comment by Zulko** [comment]
[The wikipedia article](https://en.wikipedia.org/wiki/Code_coverage). Now I don't know exactly how coveralls.io decides what is code and what is not, so I woulnd't attach too much importance to the small changes it announces (+-1%) and use it more as a general indicator.

I can see two main uses: (1) if the test suite gets refactored, ensure that it still covers as much features as before. (2) if a contributor adds code introducing many new features, ensure that the pull request is contains tests that properly cover the new code.

**Pull request merged**
