### PR TITLE
Use six to address py2/py3 urllib.urlretrieve module change.

### PR DESCRIPTION
**Pull request by Who8MyLunch**

### CODE REVIEW

**Comment by carlodri** [comment]
Sorry I'm mostly py-ignorant, but why not simply say:
```python
from urllib.request import urlretrieve
```
is it a matter of `python2`/`python3` compatibility?

**Comment by Who8MyLunch** [comment]
You have it right @carlodri .  The six library makes it easy for a single codebase to easily support both Python 2 and Python 3.

**Comment by Zulko** [comment]
Thanks for the report @Who8MyLunch ! What is the bug exactly ? Does it only bug when you call the downloader module, or does this prevent installation with Python 3 ?

I am a little against adding a new dependency. Could this bug be solved with a with/try statement ?

**Comment by Who8MyLunch** [comment]
@Zulko The bug was in the form of an import error when importing editor.py. The module `urllib.urlretrieve` does not exist in Python 3.  Instead you have `urllib.request.urlretrieve`.

This is just as easily addressed via try: statement.  I'll do that tonight when I get home.

**Comment by Zulko** [comment]
So it has been broken one month for Py3 users ??? Wow, I definitely need a test suite (I have an unofficial one actually, I just forgot to run it).

**Comment by carlodri** [comment]
It is broken only if the user updates the package explicitly (like me), or
for new users. Thanks @Zulko, moviepy is a great package!

**Comment by Zulko** [comment]
I corrected it (on github and pypi). tell me guys if it works for you.

**Comment by Who8MyLunch** [comment]
It works fine for me!

**Comment by Zulko** [comment]
Ok, so I close this one.

**Comment by carlodri** [comment]
Confirmed working on Mac OS X, thanks, will test on Win8x64 in the afternoon and report back.

**Pull request closed without merging**
