### PR TITLE
Allow for ffmpeg additional params when writing videoclip audio

### LINKED ISSUE #1493: Use ffmpeg additional params writing videoclip audio
From suggestion [here](https://github.com/Zulko/moviepy/pull/970#discussion_r403547125), this should be implemented with `audio_ffmpeg_params` argument in `write_videofile` method.

### PR DESCRIPTION
**Pull request by zpavloudis**
- [ ] I have provided code that clearly demonstrates the bug and that only works correctly when applying this fix
- [x] I have added suitable tests demonstrating a fixed bug or new/changed feature to the test suite in `tests/`
- [x] I have properly documented new or changed features in the documentation or in the docstrings
- [ ] I have properly explained unusual or unexpected code in the comments around it

I was searching for my first issue to contribute and have made an attempt on [#1493](https://github.com/Zulko/moviepy/issues/1493) following the comments suggestions. 

Best

Closes #1493

### CODE REVIEW

**Comment by zpavloudis** [comment]
@mondeja test suite fails as cannot find ImageMagick on the Windows version.
I dont think this has something todo with my PR per se?

Best !

**Comment by mondeja** [comment]
Looks good overall, but the testing seems incomplete to me. Could you add a test case for a valid argument?

**Review by mondeja — CHANGES_REQUESTED** [review]
Looks good overall, but the testing seems incomplete to me. Could you add a test case for a valid argument?

**Comment by zpavloudis** [comment]
> 
> 
> Looks good overall, but the testing seems incomplete to me. Could you add a test case for a valid argument?

Hi @mondeja , thank you for your input.
Commit https://github.com/Zulko/moviepy/pull/1666/commits/9f12f4e088d575b9d83e29ecea78755b1620e69e adds test 1493 in test_PR.py that addresses this by expecting OSError "Invalid argument" from ffmpeg when passed invalid _extra_ parameters to ffmpeg. This satisfies the requirement to pass additional audio clip params to ffmpeg when writing a video file.

If you change [$143](https://github.com/Zulko/moviepy/pull/1666/commits/9f12f4e088d575b9d83e29ecea78755b1620e69e#diff-36113ced1b010df0191c7361b075fa14770eebbb96d1b4fdcc738f20f5689362R143) to `audio_ffmpeg_params=["-af", "acrusher=.1:1:64:0:log"],` and run the test - its creates a new video file in the root directory with distorted audio as applied by the [acrusher ](https://ffmpeg.org/ffmpeg-filters.html#toc-acrusher) filter set by `-af` ffmpeg param.

I thought its best to test against ffmpeg stderr instead of say checking to see if write_videofile successful.

**Comment by mondeja** [comment]
> If we change $143 to audio_ffmpeg_params=["-af", "acrusher=.1:1:64:0:log"], and run the test - it creates a new video file in the root directory with distorted audio as applied by the acrusher filter set by -af ffmpeg param.

Please, create a test using these arguments. Write the outputted video file into temporal directory. See other tests for reference.

**Comment by zpavloudis** [comment]
Happy new year. Change for ```
test_PR_1493
``` commited as requested.

**Comment by keikoro** [comment]
Thanks, @zpavloudis! Looks like the failing format check is due to another file (noticed this on another PR as well).

**Comment by keikoro** [comment]
@zpavloudis The files (plural now) which made the code format checks fail have now been fixed. If you rebase `master`, we can have all the automated checks run over your PR again.

**Comment by keikoro** [comment]
@zpavloudis Hi, a few things got merged today, among them changes which should fix some checks that were broken. If you rebased the current master and pushed your changes again, that'd make it possible to rerun the workflows.

**Comment by zeantsoi** [comment]
This branch is certainly stale at this point, but was there a reason it was not merged upon [8186c67](https://github.com/Zulko/moviepy/pull/1666/commits/8186c67d4df9750012b339110e346a85f63daa52)? The `audio_ffmpeg_params` functionality would be a welcome addition and I'd be happy to resurrect this PR (e.g., rebase and test) so long as it'd receive review and there wasn't an overarching reason why this PR has been inactive after two years.

cc: @zpavloudis

**Comment by OsaAjani** [comment]
A similar feature have actually been added with the v2, thanks for your work and sorry this have taken so long, that was a good PR, we will try to do better next time !

**Pull request closed without merging**
