### PR TITLE
Documentation rework

### PR DESCRIPTION
**Pull request by tburrows13**
Continuation of #1438 after I messed that one up.

See https://moviepy-tburrows13.readthedocs.io/en/improve-docs/index.html for a live build of this branch.

### CODE REVIEW

**Comment by tburrows13** [comment]
Is there a way to disable the Flake8 line length checking for the examples? I'd rather not change them if possible.

**Comment by mondeja** [comment]
> Is there a way to disable the Flake8 line length checking for the examples? I'd rather not change them if possible.

I've never found the way, but it should be possible to ignore lines using regexes by writing a plugin.

**Comment by mondeja** [comment]
I'm introducing `pydocstyle` checking with `flake8-docstrings` and `flake8-rst-docstrings` ignoring some rules that are too much intrusive. Watching your progress I think they won't collide with each other.

**Comment by keikoro** [comment]
Hmm, the logs of the checks have expired, is there a way to make them run again (that I'm not seeing)? I'm assuming this wasn't merged because one of them failed? @tburrows13

**Comment by keikoro** [comment]
Ok, so I'm not seeing any `Rerun` buttons here as suggested on SO, I'm guessing those are only available to the person who opened a PR. Force-pushing an empty commit would be another option for an OP to trigger checks again.

Looks like the only option available to co-maintainers is a hack – closing and reopening an issue.

**Comment by mondeja** [comment]
> I'm assuming this wasn't merged because one of them failed?

It seems a WIP.

**Comment by tburrows13** [comment]
I'm still planning to revisit this and finish it off... I expect in December I can do this and finish off all the other 2.0 things to finally get it released!

**Comment by OsaAjani** [comment]
Thank you for your contributions and for reporting issues in this repository. With the release of v2, which introduces significant changes to the codebase and API, we’ve reviewed the backlog of open PRs and issues. Due to the length of the backlog and the likelihood that many of these are either fixed or no longer applicable, we’ve made the decision to close all previous PRs and issues.

If you believe that any of these are still relevant to the current version or if you'd like to reopen a related discussion, please feel free to create a new issue or pull request, referencing the old one.

Thank you for your understanding and continued support!

**Pull request closed without merging**
