### PR TITLE
Adding CI testing with Python 3.7

### PR DESCRIPTION
**Pull request by tburrows13**

### CODE REVIEW

**Comment by mbeacom** [comment]
@tburrows13 Until 3.7 support is officially released on Travis, you'll need to either pull down the latest 3.7 release or use `3.7-dev` to ensure the CI tests pass.

**Comment by tburrows13** [comment]
I noticed that 3.7 had been released today, but yes, as you say, it clearly hasn’t had support from Travis yet.

**Comment by mbeacom** [comment]
@tburrows13 If you'd like an example of a working 3.7 travis config, feel free to check out https://github.com/gitcoinco/web/pull/1572

Specifically:  https://github.com/gitcoinco/web/pull/1572/files#diff-354f30a63fb0907d4ad57269548329e3R2

**Comment by mbeacom** [comment]
Since you're testing so many python versions, you could simply use the matrix provided here:

https://github.com/travis-ci/travis-ci/issues/9815#issuecomment-402045581

**Pull request closed without merging**
