### PR TITLE
issue-212: add rotation info from metadata

### PR DESCRIPTION
**Pull request by taddyhuo**
Get the rotate information from the video metadata. This is really useful for processing Quicktime video (like iPhone videos).

### CODE REVIEW

**Comment by earney** [comment]
online 35, should that be infos (with an s) instead of info?

**Comment by taddyhuo** [comment]
I am sorry, that's typo~

**Comment by earney** [comment]
@taddyhuo   do you have a sample video file that has rotation info in it?  I'd like to create a test for your push request (or you can create one if you want too.  look at tests/test_PR.py if you are interested.  If you want help uploading a small video clip, I can help with that too.  Just let me know.

**Comment by taddyhuo** [comment]
Hi @earney , I love to create a test case for my pull request. And I definitely have a video with rotation info. How do I upload my video though?

**Comment by earney** [comment]
the maintainers of the project want to keep this repo small, so we created another repo called earney/moviepy_media to store the videos.  [https://github.com/earney/moviepy_media](https://github.com/earney/moviepy_media)    fork the earney/moviepy_media repo, add your video at videos/tests/ and if you don't mind,  edit the sources.txt file in that directory, add the name of your video, along with where you got the video (just in case there is an issue sometime in the future with copyrights,etc).

**Comment by earney** [comment]
one last thing, in the zulko/moviepy repo, open tests/download_media.py, and add the location of your file from the earney/moviepy_media like the other calls you see in this file.  Let me know if you need some help.  This is a bit complicated..

**Comment by taddyhuo** [comment]
@earney You know what? I just check the existing video in your test folder (fire2.mp4), and it has rotation info!!! I can just use that video for my test case!! Problem solved!

**Comment by earney** [comment]
awesome!  That makes things much easier!

**Comment by taddyhuo** [comment]
@earney Thanks... I made too many easy mistakes today...

**Comment by earney** [comment]
No worries... Just earlier this week, I had to commit about 1/2 dozen times before I got things right! :)

**Comment by earney** [comment]
Thanks.  I'll merge this right away!

**Comment by Gloin1313** [comment]
Thank you so much for adding this! I had a lot of problems with finding the rotation of a video, and I used an awful (and slow) hack using ffprobe to get the rotation metadata. I would have added this myself at some point (we had a bit of discussion about it), but this is great!
I was the one who added fire2.mp4 to the tests, and I choose one that was portrait for this reason, for when I added this.

**Comment by taddyhuo** [comment]
@Gloin1313 Thank you for your fire2.mp4! It saved me tons of time for testing my code.

@earney May I ask what's the day for next release? Thanks.

**Comment by earney** [comment]
we released version 2.3.1 late last week.  I'm not sure when 2.3.2 will be released.

**Comment by Gloin1313** [comment]
@taddyhuo The release milestone says it will be by 19 April (https://github.com/Zulko/moviepy/milestone/3). Not sure who put that there, but seems like a reasonable date.

**Comment by earney** [comment]
I would have to guess that @mbeacom put that there..

**Pull request merged**
