### PR TITLE
Fix libavformat compatiblity break

### LINKED ISSUE #1714: Changes in FFmpeg libavformat break FFmpegInfosParser
#### Expected Behavior
`FFmpegInfosParser.parse` can parse FFmpeg output.

#### Actual Behavior
`FFmpegInfosParser.parse` fails to parse FFmpeg output starting with commit [b7251ae](https://github.com/FFmpeg/FFmpeg/commit/b7251aed46f5ac96fe65c1c68ddac44b07429467), which reduced indentation for streams.

#### Steps to Reproduce the Problem
Point MoviePy to FFmpeg executable with the mentioned revision or newer and run `FFmpegInfosParser.parse`.

#### Specifications
- Python Version: 3.9.9
- Moviepy Version: 2.0.0.dev2 8eaf3f0
- Platform Name: Linux
- Platform Version: Fedora 34

#### Additional Info
ffmpeg 4.2.2 (imageio) output:
```
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'clip.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.12.100
  Duration: 01:00:00.00, start: 0.000000, bitrate: 1222 kb/s
    Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p, 1280x720 [SAR 1:1 DAR 16:9], 1221 kb/s, 25 fps, 25 tbr, 12800 tbn, 50 tbc (default)
    Metadata:
      handler_name    : VideoHandler
At least one output file must be specified
```
ffmpeg 4.4.1 (system) output:
```
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'clip.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.12.100
  Duration: 01:00:00.00, start: 0.000000, bitrate: 1222 kb/s
  Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p, 1280x720 [SAR 1:1 DAR 16:9], 1221 kb/s, 25 fps, 25 tbr, 12800 tbn, 50 tbc (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
At least one output file must be specified
```
There are other commits changing the output format too, but the mentioned one is the most problematic one.

### PR DESCRIPTION
**Pull request by B3QL**
https://github.com/FFmpeg/FFmpeg/commit/b7251aed46f5ac96fe65c1c68ddac44b07429467

Close #1714

- [x] I have provided code that clearly demonstrates the bug and that only works correctly when applying this fix
- [x] I have added suitable tests demonstrating a fixed bug or new/changed feature to the test suite in `tests/`
- [x] I have properly documented new or changed features in the documentation or in the docstrings
- [x] I have properly explained unusual or unexpected code in the comments around it

### CODE REVIEW

**Review by mondeja — APPROVED** [review]
Thank you!

**Review by mondeja — CHANGES_REQUESTED** [review]

**Review by mondeja — APPROVED** [review]
Great, thank you! :+1:

**Comment by B3QL** [comment]
Thanks for the quick feedback loop! Do you have some ETA for the next release?

**Comment by B3QL** [comment]
> No idea, I haven't rights in PyPI for this project so I can't release it. I'm just installing from master or refs using GIT urls.

I'm doing the same ;) but would be nice to have a regular release from time to time. The last official release was 1 year ago (2020-05-07).

@tburrows13 is there an ETA for the next release? Can you also consider granting PyPI access for @mondeja since he is actively maintaining the project?

**Comment by tburrows13** [comment]
Hello, thanks both for your contributions!

Basically I had a plan for future pre-releases and the v2.0 release (most of which is written in #1089) but a few of the tasks that were blocking the next release never got completed. I'm still interested in returning and finishing those tasks - hopefully at the end of June, but it won't be before then.

I do have PyPI access myself but not enough to grant @mondeja access, that would need @Zulko. Or wait a month or so until I can do the next pre-release.

**Comment by B3QL** [comment]
> Basically I had a plan for future pre-releases and the v2.0 release (most of which is written in #1089) but a few of the tasks that were blocking the next release never got completed and my life got even more busy! I'm still interested in returning and finishing those tasks - hopefully at the end of June, but it won't be before then.

Thanks for your contributions so far! It's understandable that the side OSS project is often time-consuming and it's harder to commit more free time over time.

The end of June looks decent, keeping my finger crossed ;) Any clue about the date for the 2.0.0 release? Or what needs to be delivered until it can be shipped?

> I do have PyPI access myself but not enough to grant @mondeja access, that would need @Zulko. Or wait a month or so until I can do the next pre-release.

Waiting a month or more it's not a problem here. I see it more as a way of reducing the bus factor and enabling people that want to get more involved. The project is very successful  - 15,233 repositories use it, 9.2k stars and it would be great to have some regular releases.

@Zulko please consider sharing more power and responsibility with current contributors, thanks!

**Comment by tburrows13** [comment]
Before v2.0.0, as far as I remember it is the 2 outstanding things from https://github.com/Zulko/moviepy/issues/1089#issuecomment-686136473 and the documentation rework (which I think I nearly finished). The original comment in #1089 had some more things but I don't think that they're as important and I'd be happy to release without them.

**Pull request merged**
