### PR TITLE
Added AAC codec to mp4

### PR DESCRIPTION
**Pull request by jeromegrosse**
Fix of the issue #344

### CODE REVIEW

**Comment by mbeacom** [comment]
@jeromegrosse Thanks for the PR.

[AAC](https://trac.ffmpeg.org/wiki/Encode/AAC) is an formatting/codec type for Audio (this extensions dict defines `video` codec types.  Just looking for some clarification.
What issue does this resolve?

**Comment by ping** [comment]
I'm not the OP, but the problem is specified in #344
Without this PR, I cannot specify aac as the audio codec in ``write_videofile()``

```python
vidclip.write_videofile(output_file, codec='libx264', audio=True, audio_codec='aac')
```

**Comment by earney** [comment]
@mbeacom,  should we merge this pull request or should we look at adding an audio_codec to the dictionary?

**Comment by jeromegrosse** [comment]
@mbeacom
The `extention_dict` dictionnary is used by [find_extention](https://github.com/jeromegrosse/moviepy/blob/00e911a617eaff63f8e87c6e069d087a8ff6186e/moviepy/tools.py#L155) which is itself used by [write_videofile](https://github.com/jeromegrosse/moviepy/blob/00e911a617eaff63f8e87c6e069d087a8ff6186e/moviepy/video/VideoClip.py#L309) when looking for the right codec to use for the audio file. This PR allows the possibility to use AAC and MP4.

The way I understood it, `extention_dict` is used to instinctively look up the audio and video codecs. Maybe it is semantically wrong though, and we should use two different dictionary, one for video codecs and one for audio codecs?

**Comment by mbeacom** [comment]
@jeromegrosse From the look of it, we should probably split up the dictionaries.  This will require additional refactoring throughout the codebase to split up the dictionaries. @earney Maybe we merge this and open a separate issue to track potentially splitting up the codec dictionaries?

**Comment by earney** [comment]
will do.

**Pull request merged**
