### PR TITLE
Update CI ImageMagick version

### PR DESCRIPTION
**Pull request by tburrows13**
People will be using ImageMagick v7 with moviepy, so we should test against it.

### CODE REVIEW

**Comment by mondeja** [comment]
This change is doing a lot of different things unrelated to ImageMagick version update. Could you consider separate them in another pull request?

**Comment by tburrows13** [comment]
Oops it seems to have got mixed up with #1176. Probably a faulty rebase or something. I'll sort it out (but this PR probably won't be needed once I've finished the new text clip and imagemagick is gone).

**Comment by mondeja** [comment]
> but this PR probably won't be needed once I've finished the new text clip and imagemagick is gone

If so, could you check it and close if not needed?

**Comment by tburrows13** [comment]
Yeah, this PR is completely messed up. I'll close on the assumption that it will be not needed in the future.

**Pull request closed without merging**
