### PR TITLE
Bug-fix: Slide_out: fixed computation of position

### PR DESCRIPTION
**Pull request by knezi**
Slide_out didn't do anything before.

Can you please estimate when this gets into a release?

### CODE REVIEW

**Comment by tburrows13** [comment]
Hi, thanks for this. Do you think this is related to #649? Is there a similar problem in `slide_in`?

**Comment by tburrows13** [comment]
I'm just trying this fix out and I don't think it works, but I may be misunderstanding the function.

I'm using this code, taken largely from the example in the docstring:

```from moviepy.editor import *
c1 = ColorClip((1500, 1000), color=(255, 0, 0))
c2 = ColorClip((1500, 1000), color=(255, 255, 0))
c3 = ColorClip((1500, 1000), color=(0, 255, 0))
clips = [c1, c2, c3]
sclips = [clip.set_duration(4).fx(transfx.slide_out, 1, 'bottom') for clip in clips]
c = concatenate_videoclips(sclips, padding=-1)

c.write_videofile("test.mp4", fps=24)
```

Can I see your code please?

**Comment by knezi** [comment]
In the doc string there's written you have to use it inside CompositeVideoClip. My code:

```
mask=ColorClip(clip2.size, color=1, ismask=True, duration=clip2.duration)\
                        .fx(transfx.slide_in, \
                                duration=tr_time, side=fr)
mask=CompositeVideoClip([mask], ismask=True, size=clip2.size)
clip2=clip2.set_mask(mask)
```


But you don't have to use it in mask obviously. So if you do something like: [CompositeVideoClip([clip.....]) for clip in clips], it should work.

No, #649 is not related to this. Slide_in works, but again, you have to include it in CompositeVideoClip.

**Comment by knezi** [comment]
I added the fixed examples. (And missing required dependency).

**Comment by tburrows13** [comment]
Thank you for editing the examples, that’s really helpful. Why have you mentioned requests as a dependency? According to setup.py, it’s only needed when running the test suite.

**Comment by knezi** [comment]
When I cloned the git repository and ran `import moviepy` in python, I got an error that requests is missing. However, I'm not getting this anymore. Sorry, please disregard this commit.

**Comment by knezi** [comment]
I'm still trying to understand how pull requests work on github. Sorry for confusion. My last commit was automatically added here. So, commits `slide_out` and `fix examples` are correct and they're fixing what the PR is about.
The commit `Added dependency` is wrong and shall be disregarded.
My last commit `Fix: concatenate` is correct and fixes different part of code.

**Comment by mgaitan** [comment]
hey guys. IMHO this patch is very important and almost done. would you like I reopen it squashing the correct commits? or could you @tburrows13 do it?

**Comment by knezi** [comment]
@mgaitan Yes, I feel the same. I can also do it if you can guide me what to do.

**Comment by mgaitan** [comment]
@knezi what you could do is to rebase your branch against the parent of your first commit. 

```
 git rebase -i 6cbd4f34773
```

this will open your editor with the list of commits and you can pick / squash / drop them following the intructions commented in the same screen.

As this operation will assigns new hashes for the resulting commits (i.e it rewrites the history) you will need to force the push with "-f".  

Alternatively, create a new branch from `master`, and cherry-pick the right commits. Then close this PR and reopen a new one from the clean branch. 

(Btw, it's always a good practice to create a branch for your feature/bugfix and avoid to open prs from your master to the official's master branch.)

**Comment by tburrows13** [comment]
Yep, we need to clean up this PR before merging, or start anew. What @mgaitan sugggested looks good. @knezi, if you need a hand with working with git, feel free to post on the [moviepy Gitter channel](https://gitter.im/movie-py/Lobby) (though it’s currently down for maintenance 😔). We try to have a separate PR for each feature/bugfix.

**Pull request closed without merging**
