### PR TITLE
Subtitles support

### LINKED ISSUE #922: SubtitlesClip don't add last line
Hi, when I add subtitles to a video, the last line don't appear on the video, this is the code I use:

```
myvideo = VideoFileClip(res_dir + "video.avi")
	
	generator = lambda txt: TextClip(txt, 
									font='Georgia-Regular',
									fontsize=52, 
									color='white',
									stroke_color='black',
									stroke_width=3,
									size=myvideo.size,
									method='caption',
									align="South") 
	sub = SubtitlesClip(res_dir + "subs.srt", generator)

	final = CompositeVideoClip([myvideo, sub])
	final.to_videofile(res_dir + "video.mp4", fps=myvideo.fps)
```

The srt file have a last line of text and the time interval of this line is inside the duration of the video, but it don't appear on the final video.

  - Python Version: 3.7
  - Moviepy Version: 1.0.0
  - Platform Name: Windows
  - Platform Version: 7

### LINKED ISSUE #1511: How do I can auto-break subtitles, and write it's in a new line?
Hello everyone.
I have too long text for subtitles, and I need to write that text in 2 subtitle lines. 
How do I can make it? 
Maybe, need to remake generator? 
```python
def __init__(self, txt=None, filename=None, size=None, color='black',
             bg_color='transparent', fontsize=None, font='Courier',
             stroke_color=None, stroke_width=1, method='label',
             kerning=None, align='center', interline=None,
             tempfilename=None, temptxt=None,
             transparent=True, remove_temp=True,
             print_cmd=False):
```
For now I have generator:
```python
lambda txt: TextClip(txt, fontsize=10, color="white", align="center")
```
And I by generator create subtitles:
```python
subs = SubtitlesClip(self.__video_subtitles, make_textclip=self.__subtitles_generator).set_position("bottom")
```

Subtitles go abroad of video

### PR DESCRIPTION
**Pull request by vsquareg**
This pull request is to work on the _currently_ experimental subtitle support module.

Tasks to be accomplished _(as of now)_:

- [x] Closes #922 
- [x] Closes #1511 
- [x] Add standard HTML tags support for parsing of srt: bold, italics, underline, strikethrough.

The separate "generator" aspect of the subtitle module was restricting the HTML tags and auto_wrap part (closes #1511), hence, a different approach had to be taken. This breaks backward compatibility, but the module was mentioned as experimental, so hopefully, this won't be an issue.

### CODE REVIEW

**Comment by tburrows13** [comment]
Hello, thanks for the contribution! Breaking compatibility is fine, because when finished, this would be in v2.0, which is breaking compatibility in lots of other places as well. I'd appreciate a brief guide to porting code from old to new that I can put into the transition guide docs when they are done (WIP [here](https://github.com/Zulko/moviepy/pull/1482/files#diff-0f01df6b027551accb126ec87775d610baef5981558555857da7e34492953212)).

Let me know when its done and I'll review it properly.

**Comment by vsquareg** [comment]
### Changes:
Earlier SubtitleClip required a separate generator to be passed a parameter:

```
generator = lambda text: TextClip(text, font='Georgia-Regular', font_size=24, color='white')
sub = SubtitlesClip("subtitles.srt", generator)
```
This restricted formatting of text while generating the SubtitlesClip to accommodate standard HTML tags used in subtitles (bold, italics, underline, strikethrough).
Hence, the generator was removed, and the parameters can now be directly passed into the SubtitlesClip class:

```
sub = SubtitlesClip("subtitles.srt", font='Georgia-Regular', font_size=24, color='white')
```

Auto-wrapping of subtitles (#1511) can now be passed as a parameter, it requires the video_width parameter:

```
sub = SubtitlesClip("subtitles.srt", auto_wrap=True, video_width=1280)
```

### Failing checks & dependencies:
For accommodating the HTML tags, _pango_ rendering method of ImageMagick is used.
_pango_ is available by-default in Linux. However, requires installation for macOS:

```
brew install pango
```

**Comment by vsquareg** [comment]
@tburrows13 if you could review this now, would love to know your thoughts.

Please let me know if any other functionality can be added to the subtitles part.

Also, is there any work being done to move away from the ImageMagick dependency?

**Comment by tburrows13** [comment]
> @tburrows13 if you could review this now, would love to know your thoughts.
> 
> Please let me know if any other functionality can be added to the subtitles part.
> 
> Also, is there any work being done to move away from the ImageMagick dependency?

Unfortunately I don't have time for a couple of weeks to properly review it. You can see in #1472 the discussion about removing ImageMagick. Basically it will happen very soon, I'll likely do it in the next couple of months if no one else has before then. This PR would need to work with ImageMagick, so I'm not sure about the HTML tags bit you mentioned.

**Review by mondeja — APPROVED** [review]
I think that we can merge this testing it properly. Thank you for the contribution @vsquareg! I will make a few changes and will be ready to merge :+1:

**Comment by mondeja** [comment]
Could you check [this error of the build](https://github.com/Zulko/moviepy/pull/1512/checks?check_run_id=2722684853#step:8:1609) @vsquareg? I'm not sure how to install it on MacOS, do you know?

**Comment by keikoro** [comment]
Pinging you, @vsquareg, for follow-up!

**Comment by keikoro** [comment]
@vsquareg Hi, a few things got merged today, among them a fix for broken checks. If you rebased the current master and pushed your changes again, it'd be possible to rerun the workflows for your PR to see where it's at.

**Comment by Resocram** [comment]
@vsquareg Any update on the status of the PR?

**Comment by 8enjam1n** [comment]
Hey ? I can't add a stroke to subtitles ? Someone know how to do it ? Thx :)

**Comment by OsaAjani** [comment]
Thank you for your contributions and for reporting issues in this repository. With the release of v2, which introduces significant changes to the codebase and API, we’ve reviewed the backlog of open PRs and issues. Due to the length of the backlog and the likelihood that many of these are either fixed or no longer applicable, we’ve made the decision to close all previous PRs and issues.

If you believe that any of these are still relevant to the current version or if you'd like to reopen a related discussion, please feel free to create a new issue or pull request, referencing the old one.

Thank you for your understanding and continued support!

**Pull request closed without merging**
