### PR TITLE
Added grayscale, single channel input support

### PR DESCRIPTION
**Pull request by racinmat**
- [x] If this is a bugfix, I have provided code that clearly demonstrates the problem and that works when used with this PR
- [x] I have added a test to the test suite, if necessary
- [x] I have properly documented new or changed features in the documention, or the docstrings
- [x] I have properly documented unusual changes to the code in the comments around it
- [ ] I have made note of any breaking/backwards incompatible changes

there are no BC breaks since this only adds new functionality. Added single test for this feature.

### CODE REVIEW

**Comment by tburrows13** [comment]
Linking #190, #552.

**Comment by caniko** [comment]
I need this.

**Comment by tburrows13** [comment]
Yep, grayscale support is definitely something we need, hopefully I'll get around to including this in v2.0. Would you happen to have an example of an image that only works with this PR @caniko or @racinmat ?

**Comment by racinmat** [comment]
I updated my fork, so this should be compatible with master. I added example image to tests, so hopefully everything will pass now.

**Comment by tburrows13** [comment]
(You can run `pre-commit install` which will set it up to that `black`, the code formatter is run on each commit).

**Comment by tburrows13** [comment]
You can run `black -t py36 .` to fix the black errors.

**Comment by tburrows13** [comment]
Nice, thanks for the image. I'll probably merge this in a few weeks. I think we're nearing the final v2.0 push :)

**Comment by racinmat** [comment]
Thanks for the tip, I was struggling a bit with my PyCharm having different opinion on code style than blake. Hopefully everything should be ok and ready for merge now. Sorry it took so long.

**Comment by tburrows13** [comment]
Yeah they don't always exactly match! Everything looks fine now, but I'd like to properly test it myself, which won't be for a couple of weeks.

**Comment by caniko** [comment]
Got some images here:
[mitochondria.tar.gz](https://github.com/Zulko/moviepy/files/6090195/mitochondria.tar.gz)

**Comment by caniko** [comment]
Got some images here: 
[mitochondria.tar.gz](https://github.com/Zulko/moviepy/files/6090200/mitochondria.tar.gz)

**Comment by tburrows13** [comment]
Thanks @caniko, that looks useful :)

**Comment by racinmat** [comment]
Any progress here? @tburrows13

**Comment by racinmat** [comment]
ping @tburrows13  or @Zulko or @mondeja

**Comment by OsaAjani** [comment]
Thank you for your contributions and for reporting issues in this repository. With the release of v2, which introduces significant changes to the codebase and API, we’ve reviewed the backlog of open PRs and issues. Due to the length of the backlog and the likelihood that many of these are either fixed or no longer applicable, we’ve made the decision to close all previous PRs and issues.

If you believe that any of these are still relevant to the current version or if you'd like to reopen a related discussion, please feel free to create a new issue or pull request, referencing the old one.

Thank you for your understanding and continued support!

**Pull request closed without merging**
