### PR TITLE
fix YouTube embeds in docs

### LINKED ISSUE #304: Broken Gallery in Documentation
The [Gallery](http://zulko.github.io/moviepy/gallery.html) page in the docs does not show soem videos, instead it triggers the browser to as to download multiple files, with then can not be downloaded because of a network error. I assume some mime type related webserver configuration error.

### PR DESCRIPTION
**Pull request by kerstin**
Fixes #304, renders #342 + #343 invalid.

### CODE REVIEW

**Comment by kerstin** [comment]
Replaces AS3 objects with iframes and gets rid of mixed content (http urls in https site).

**Comment by Zulko** [comment]
I'm not sure I understand what the problem is, the videos in the gallery work fine for me in Firefox and Chrome, is there a problem on some other browsers ? Are iframes the standard way of embedding youtube videos ?

**Comment by kerstin** [comment]
For me, the videos don't show in either browser + when opening the local versions of the files, I'm additionally experiencing the problem described by @COLABORATI in #304 (I'm prompted to download the files).

From the [YouTube docs](https://developers.google.com/youtube/player_parameters#Revision_History):

> March 9, 2015
> * The document has been updated to reflect the fact that YouTube \<object\> embeds, the YouTube Flash Player API and the YouTube JavaScript Player API have all been deprecated as of January 27, 2015. A deprecation warning appears in several sections of this document to help point readers to the IFrame Player API as an alternative.

**Comment by kerstin** [comment]
From Chrome's console:
`Mixed Content: The page at 'https://zulko.github.io/moviepy/gallery.html' was loaded over HTTPS, but requested an insecure resource 'http://youtube.com/v/zJtWPFX2bA0?rel=0'. This request has been blocked; the content must be served over HTTPS.`

I'm also getting *warnings* for images, but apparently browsers aren't as strict about those, so they still show up.

**Comment by kerstin** [comment]
I have no idea why the videos show for you, @Zulko, because they really shouldn't. Perhaps different security settings? Maybe you allowed mixed content for your docs at some point (if that is even an option)?

**Comment by kerstin** [comment]
When I try to access the `http` version of the docs, I'm actually also getting the download prompts (except Chrome doesn't just display the Download dialogue but pops up this message).

screen shot 2017-02-24 at 10 38 20

**Comment by kerstin** [comment]
(My browsers default to the secure version of the docs page.)

**Comment by kerstin** [comment]
I'm also getting the download prompts on mobile. Have you tried opening the docs with a browser you haven't used for development? (I'm not sure if/how being logged in could additionally affect this.)

**Comment by kerstin** [comment]
Just leaving a note here that @Zulko approved this PR on Gitter.

**Comment by earney** [comment]
Awesome!..  Lets merge this puppy then! :)

**Pull request merged**
