### PR TITLE
 Fix stretched vertical video, add ability to disable autorotate

### PR DESCRIPTION
**Pull request by cvn**
This PR fixes stretched video from issue #682, and adds the ability to disable autorotate for VideoFileClip, ImageClip, and ImageSequenceClip.

VideoFileClip now has an ffmpeg_params argument, and setting it to `['-noautorotate']` will disable autorotation. ImageClip and ImageSequenceClip now have an imageio_params argument. Use `{'exifrotate': False}` to disable autorotation.

I've updated the version of ffmpeg used on Travis from 2.4.3 to 3.3.3 by changing the apt repo. The [new one](https://launchpad.net/~mc3man/+archive/ubuntu/trusty-media) comes from http://ffmpeg.org/download.html. I did this because the tests for autorotate require ffmpeg >=2.7. If it's better to keep the older version, I could skip the tests instead.

Thanks to @taddyhuo for laying the groundwork for this in #529. And thanks to @bobatsar for his work in #577, which started me on this path. Also, thanks to the moviepy maintainers for the excellent project organization. :)

EDIT: I pushed new commits since I opened this PR.

### CODE REVIEW

**Comment by cvn** [comment]
The failures on Travis are from my new tests, when `-noautorotate` is passed to ffmpeg. This indicates that the version of ffmpeg on the CI server is older than 2.7. Can anyone confirm this?

In my local environment, these tests pass. I'm using a docker instance built from the Dockerfile in this repo. It has ffmpeg 3.3.1 installed.

The simplest thing would be to skip these particular tests on Travis, but if someone has a better idea, let me know.

**Comment by cvn** [comment]
I added a commit which changes the ffmpeg repo used for Travis from [ffmpeg-next](https://launchpad.net/~kirillshkrogalev/+archive/ubuntu/ffmpeg-next) to [trusty-media](https://launchpad.net/~mc3man/+archive/ubuntu/trusty-media). This updates ffmpeg from 2.4.3 to  3.3.3, and resolves the CI failures. There is still one failure in the python 3.3 environment, but it appears unrelated to this PR.

**Comment by cvn** [comment]
Hi, is there anything I can do to help move this forward?

**Comment by wisefool769** [comment]
any update on merging this?

**Comment by tburrows13** [comment]
If anyone is wanting to take this forward, see https://github.com/Zulko/moviepy/projects/5 for context. There are still definitely issues with certain rotated videos, but I have no idea if this would fix them.

**Comment by mondeja** [comment]
This seems too much for me to fix the error, i think #577 solution is better. Feel free to reopen this if you don't agree.

**Pull request closed without merging**
