### PR TITLE
Tests for loop using BitmapClip #1368

### PR DESCRIPTION
**Pull request by somstrom**
I added some tests for loops using BitmapClip and they passed.

- I have added suitable tests demonstrating a fixed bug or new/changed feature to the test suite in `tests/`
- I have properly documented new or changed features in the documentation or in the docstrings
- I have formatted my code using `black -t py36`

### CODE REVIEW

**Comment by somstrom** [comment]
I added test for infinite loop and tests for fadein using BitmapClip

**Comment by somstrom** [comment]
I would like to fix loop issue, so I got one question.

Loop function is called 2 times so previous_duration is rewritten. But i can't figure out why it is called 2 times yet.

I have replaced `previous_duration` with numeric value of clip duration and it works.

**Comment by tburrows13** [comment]
Check the Gitter for discussion - someone else is also working on it :)

**Comment by tburrows13** [comment]
Good job, I'm happy to merge.

**Pull request merged**
