### PR TITLE
Add fps_source option for #404

### PR DESCRIPTION
**Pull request by Gloin1313**
In #404 Zulko suggested a `fps_source` parameter for `VideoFileClip`, to tell it to read `fps` instead of `tbr` if required.

I'm not sure how to implement the test (download the file), so if someone could let me know how, or do it yourself, that would be great!

And is it ok to declare the functions inside the main function? I did it like that so that they would be right before they are called for reference, but it might impact performance a little. Your decision.

### CODE REVIEW

**Comment by earney** [comment]
add the following to the top of your test files:

```
# must have to work on travis-ci
import sys
sys.path.append("tests")
import download_media

def test_download_media(capsys):
    with capsys.disabled():
       download_media.download()
```

then you can use any of the files that are contained in the download_media.py file.  These will be downloaded and placed in your ./media directory.   if you want an extra media file added, we can look at modifying the download_media.py script, and also adding the media file to the earney/moviepy-media repo.

Let me know if you have additional questions.

**Comment by Gloin1313** [comment]
The only video you have is the "Big Buck Bunny" one, which I have downloaded to test, and it has the same fps as tbr, which makes it unsuitable for testing. Can we add a different one? One that was actually filmed on a camera would probably be best.

**Comment by earney** [comment]
yes, we can add more videos.  Do you have one in mind?

**Comment by Gloin1313** [comment]
I can't seem to find any videos on youtube where they are different. Maybe youtube uniforms them as they are uploaded?

**Comment by Gloin1313** [comment]
Are there any other ways we can do it? e.g. load a video into Travis?

**Comment by earney** [comment]
we load a video up to earney/moviepy-media.  When Travis runs the tests, the first test in the python file is a test that sees if all the media files have been downloaded.  If not, they are downloaded to the media directory.

**Comment by Gloin1313** [comment]
So is there any way for me to use my own files in the test without download_media having to get them from youtube?

**Comment by earney** [comment]
download_media can download any url, so if you have a location, we can download it.  I created a repo just for media for this project called earney/moviepy_media, so that the media will not get moved like it does from sources that we do not control, etc.

**Comment by earney** [comment]
@gloin1313  I'm not aware of any other way of using our own files, but to use the download_media script I created.  If you can find some other way, I'm interested.

**Comment by Gloin1313** [comment]
@earney Ok, I've uploaded a video to vimeo here: https://vimeo.com/210765693
Its not a slo-mo, but ffprobe tells me it has 10.51 fps, 90k tbr. Re-downloaded it from vimeo and it still has those settings, so it should work fine.  Is it ok if you add this to `download_media`? Then when you've done that I'll write the test.

**Comment by earney** [comment]
its located at https://github.com/earney/moviepy_media/tree/master/tests/videos as fire2.mp4.  Let me know if you need some additional help.

**Comment by earney** [comment]
Aweseome!..   @Gloin1313   I think this is ready to merge..  :)

**Comment by Gloin1313** [comment]
Great! One thing I wasn't sure about; is defining a function inside of the function recommended? Do we agree readability over speed?

**Comment by earney** [comment]
yes, readability > speed

**Pull request merged**
