### PR TITLE
Log ffmpeg command

### LINKED ISSUE #270: write_videofile should log ffmpeg command
For debugging purposes it would be nice if write_videofile would log the ffmpeg command used.  Not sure where else it is used, but the actual ffmpeg command used can be very helpful

### PR DESCRIPTION
**Pull request by thenewguy**
Fixes #270

### CODE REVIEW

**Comment by thenewguy** [comment]
Can't seem to find b3a5f5c591885f9d1153eed0c9e1445eb793325b for cherry pick or merging back into my branch

**Comment by thenewguy** [comment]
@tburrows13 rfc

**Comment by tburrows13** [comment]
Looks good, I'm happy to merge. Thanks for your help.

**Comment by thenewguy** [comment]
Closing in favor of #1039

**Comment by keikoro** [comment]
@thenewguy I'm thinking it might make sense to reopen this PR since the linked combined too many things and was eventually rejected.

**Pull request closed without merging**
