### PR TITLE
Rework usage of FFMPEG_VideoReader's `pos` and `lastread`; FFMPEG_AudioReader.close_proc() -> close()

### LINKED ISSUE #1078: Maybe a trick hack for the problem of "OSError: MoviePy error: failed to read the first frame of video file nCoronaVirus.mp4." exception.
When I handle some video loop processing that moviepy will raise some kind of exception just like: 

> "OSError: MoviePy error: failed to read the first frame of video file nCoronaVirus.mp4. That might mean that the file is corrupted. That may also mean that you are using a deprecated version of FFMPEG. On Ubuntu/Debian for instance the version in the repos is deprecated. Please update to a recent version from the website." 

After I search on the internet I noticed that many people meet the same problem just like me. Even though that the exception message mentioned we should update deprecated version of FFMPEG, the installment of latest version of ffmpeg still cannot resolve the problem. 
 
So I looked into the source code of .../lib/python3.7/site-packages/moviepy/video/io/ffmpeg_reader.py and do a maybe-not-so-clean hack, but it does help a lot.

Here is the hack point, i.e. comment the last two line of the close() funciton:

```
def close(self):
        if self.proc:
            self.proc.terminate()
            self.proc.stdout.close()
            self.proc.stderr.close()
            self.proc.wait()
            self.proc = None
        #if hasattr(self, 'lastread'):
        #    del self.lastread 
```

I wonder if there is a better way to resolve this exception problem, I hope to be noticed if any buddy who could patch this code in a better way. And I also hope that the source maintainers could pay some attention to this issue, for it's maybe not really a problem related to ffmpeg but the inner logic of the ffmpeg_reader.py code. 

Looking forward to the update of moviepy source. Thanks the team. ;-)

### LINKED ISSUE #1191: Warnings are suppressed by moviepy
Hi,

Thanks for the library, I think it's great.

My warnings are being suppressed/captured after I import certain `moviepy` modules. I suspect it's caused by this line:
https://github.com/Zulko/moviepy/blob/4d70eabd784a73c16ab91bc90914df99fa9cc322/moviepy/video/io/ffmpeg_reader.py#L19

### Steps to Reproduce the Problem

```
iPython 3.8.2 (default, May  6 2020, 02:49:43)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.13.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import warnings

In [2]: import moviepy

In [3]: warnings.warn('x')
<ipython-input-3-5759b8345431>:1: UserWarning: x
  warnings.warn('x')

In [4]: from moviepy.video.io.VideoFileClip import VideoFileClip

In [5]: warnings.warn('x')

In [6]:
```

### Specifications

  - Python Version: `3.8.2`
  - Moviepy Version: `1.0.3`
  - Platform Name: `macOS`
  - Platform Version: `Catalina 10.15.4`

### PR DESCRIPTION
**Pull request by tburrows13**
Closes #1078, closes #1191, closes #648.

In general, this PR simplifies the handling of `reader.pos` by updating it only when `reader.proc` is created or accessed. This keeps the 2 up-to-date with each other.

I also fixed #1078 by ensuring that when the clip is being closed only to be reopened straight away, `lastread` is not deleted. This can happen legitimately (when we need to get a frame before the previous one or when we skip far ahead), but it can also happen if the reader has been previously closed and is then called upon. I still don't know why this is allowed, so perhaps it should be removed in the future?

I renamed `FFMPEG_AudioReader.close_proc()` to `.close()` to stay consistent with `FFMPEG_VideoReader`. In the future I might look at combining these 2 classes, probably with each of them inheriting a base FFMPEG_Reader class. This will avoid duplicating the (quite complex!) code and make it easier to analyse and fix.

Finally, I removed the `logging.captureWarnings(True)` (#1191) so that the tests would work. I will probably revisit how MoviePy handles warnings/logging in the future.

- [x] I have provided code that clearly demonstrates the bug and that only works correctly when applying this fix
- [x] I have added suitable tests demonstrating a fixed bug or new/changed feature to the test suite in `tests/`
- [x] I have properly documented new or changed features in the documentation or in the docstrings
- [x] I have properly explained unusual or unexpected code in the comments around it
- [x] I have formatted my code using `black -t py36`

### CODE REVIEW

**Comment by thenewguy** [comment]
Is there anything I could do to help move this one along?  A release with this fix would be appreciated

**Comment by tburrows13** [comment]
I like to leave largish PRs open for a while in case anyone wants to review it or object to it, but I'm happy to merge this one today. Do you need it included in a pip-installable release (v2.0.0.dev2)?

**Comment by thenewguy** [comment]
@tburrows13 if that is convenient for you it would be awesome

**Comment by tburrows13** [comment]
Sure. My only holdup is that I merged #1063 but I've since decided that I wasn't so sure about that change. I need to do some more research about ffmpeg's durations and decide whether it is ok as-is, whether it should be reverted or whether #1222 is a suitable fix. Shouldn't be more than a couple of days.

**Comment by thenewguy** [comment]
@tburrows13 forgot to mention this fixed all of my expected failures around this issue! awesome work

**Comment by fancydancing** [comment]
Hi guys! Haven't you released this fix yet? No option to install it via pip?..

**Comment by tburrows13** [comment]
Hi @fancydancing, stay tuned, I'm planning a prerelease pip release this week that will include this :)

**Comment by fancydancing** [comment]
> Hi @fancydancing, stay tuned, I'm planning a prerelease pip release this week that will include this :)

Thank you! Can't wait :) we're using your cool package in production and it started causing errors when making thumbnails for videos (which is by the way strange, nothing changed there...). So this prerelease would help us a lot ) Thank you for your work!

**Comment by tburrows13** [comment]
This PR has now been included in v2.0.0.dev2. Sorry for the delay and let us know how it goes :)

**Comment by fancydancing** [comment]
Hi Tom! Upgraded to 2.0.0.dev2. Seems that it solves my problem!) But I have troubles installing it with Pipfile. It's not on PyPi, right?

**Comment by tburrows13** [comment]
It is on Pypi as a prerelease (https://pypi.org/project/moviepy/#history). With pip you can install it by using the `--pre` flag. I don't know about pipfile.

**Comment by fancydancing** [comment]
Thanks) Yes, pip install went well, will keep googling about pipfile then. Anyway, [this](https://github.com/Zulko/moviepy/issues/1323) issue is gone for me and it is great!

**Comment by josebenitezg** [comment]
Still facing the same error even if I make the upgrade.
When I trying to concatenate videos I am suceed with a small list of videos but when is bigger I face this error:


`
/home/ubuntu/anaconda3/envs/tensorflow_p37/lib/python3.7/site-packages/moviepy/video/io/ffmpeg_reader.py:161: UserWarning: In file video.mkv, 921600 bytes wanted but 0 bytes read,at frame index 0 (out of a total 24 frames), at time 0.00/1.00 sec. Using the last valid frame instead.
  UserWarning,
Traceback (most recent call last):
  File "get_s3.py", line 113, in <module>
    clips.append(VideoFileClip(filename))
  File "<decorator-gen-88>", line 2, in __init__
  File "/home/ubuntu/anaconda3/envs/tensorflow_p37/lib/python3.7/site-packages/moviepy/decorators.py", line 89, in wrapper
    return f(*new_a, **new_kw)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p37/lib/python3.7/site-packages/moviepy/video/io/VideoFileClip.py", line 109, in __init__
    fps_source=fps_source,
  File "/home/ubuntu/anaconda3/envs/tensorflow_p37/lib/python3.7/site-packages/moviepy/video/io/ffmpeg_reader.py", line 73, in __init__
    self.initialize()
  File "/home/ubuntu/anaconda3/envs/tensorflow_p37/lib/python3.7/site-packages/moviepy/video/io/ffmpeg_reader.py", line 131, in initialize
    self.lastread = self.read_frame()
  File "/home/ubuntu/anaconda3/envs/tensorflow_p37/lib/python3.7/site-packages/moviepy/video/io/ffmpeg_reader.py", line 166, in read_frame
    "MoviePy error: failed to read the first frame of "
OSError: MoviePy error: failed to read the first frame of video file video.mkv. That might mean that the file is corrupted. That may also mean that you are using a deprecated version of FFMPEG. On Ubuntu/Debian for instance the version in the repos is deprecated. Please update to a recent version from the website.`

**Comment by tburrows13** [comment]
@josebenitezg would you mind making a new issue with that information please? Are you able to provide the videofile that is causing the crash?

PS Use 3 backticks at the start and end of your code to format it properly :)

**Comment by energy888666** [comment]
我升级到最新版本

> @josebenitezg would you mind making a new issue with that information please? Are you able to provide the videofile that is causing the crash?
> 
> PS Use 3 backticks at the start and end of your code to format it properly :)

我升级到最新版本 pip install moviepy==2.0.0.dev2   还是无法解决
[这是我的视频[链接：https://pan.baidu.com/s/1MGIv86_ogIr2kZ-XYdJVkA 
提取码：8v3z](url)

**Comment by ShunLu91** [comment]
> 我升级到最新版本
> 
> > @josebenitezg would you mind making a new issue with that information please? Are you able to provide the videofile that is causing the crash?
> > PS Use 3 backticks at the start and end of your code to format it properly :)
> 
> 我升级到最新版本 pip install moviepy==2.0.0.dev2 还是无法解决 [这是我的视频[链接：https://pan.baidu.com/s/1MGIv86_ogIr2kZ-XYdJVkA 提取码：8v3z](url)

可以试试把num_workers改为1，报错频率会降低；报错后，从断点重启即可

**Pull request merged**
