### PR TITLE
Fix #1338 - Replace deprecated functions

### LINKED ISSUE #1338: Deprecation warnings
When running the test suite it reveals some deprecations:

      /home/runner/work/moviepy/moviepy/moviepy/audio/AudioClip.py:121: FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.

      /home/runner/work/moviepy/moviepy/moviepy/video/io/gif_writers.py:323: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.

Source: https://github.com/Zulko/moviepy/runs/1227641497 (under PyTest)
I think that the first one is NumPy and the second is Pillow (PIL).

It would be good to investigate and fix these 2 warnings.

### PR DESCRIPTION
**Pull request by cryptobadger**
Closes #1338.

- s/frame.tostring()/frame.tobytes()
- replace generator as source for numpy stacks with a list

I'd like to contribute and this was marked as good first request and there is no activity on this issue albeit being quite simple to fix.

### CODE REVIEW

**Comment by tburrows13** [comment]
Thanks for the PR. You can run `pip instal black` and then `black -t py36 .` on your branch to get it to pass the format check.

**Comment by tburrows13** [comment]
Don't worry about it taking lots of commits to get right, they'll all be squashed into one when they get merged in. Let us know if you need more help getting it ready for review :)

**Comment by cryptobadger** [comment]
ha! i was actually doing this. But technically i'm stuck now, since the code format check would like to reformat `test_fx.py` and `gif_writers.py` but i'm getting

```
black -t py36 tests/test_fx.py 
All done! ✨ 🍰 ✨
1 file left unchanged.
black -t py36 moviepy/video/io/gif_writers.py 
All done! ✨ 🍰 ✨
1 file left unchanged.

```

**Comment by tburrows13** [comment]
Oh that's very strange. I guess maybe you've got an outdated version of Black?

```
black --version
black, version 20.8b1
```

I've done it on my machine and pushed to your branch so it should be fixed now.

**Comment by cryptobadger** [comment]
nice, thank you!
indeed, it is 
```
black --version
black, version 19.10b0
```

which is utterly strange, since i installed it in a virtualenv minutes ago and also did 
`pip install -U black`

do you compile it from source?

**Comment by tburrows13** [comment]
> nice, thank you!
> indeed, it is
> 
> ```
> black --version
> black, version 19.10b0
> ```
> 
> which is utterly strange, since i installed it in a virtualenv minutes ago and also did
> `pip install -U black` (and, for the sake of it `pip install -U pip`)
> 
> do you compile it from source?

No, it is just from a pip install. No idea why it isn't working for you, all the releases are there: https://pypi.org/project/black/#history.

**Comment by tburrows13** [comment]
Thanks for the work. As @somstrom had the issue assigned, I shall close this one in favour of #1365.

**Pull request closed without merging**
