### PR TITLE
Small fix to resolve unicode error

### PR DESCRIPTION
**Pull request by TheShadow29**
Its a small fix for unicode errors. Solves #140 and maybe #207. To the best of my understanding (https://docs.python.org/3/howto/unicode.html) this should not cause any issues. However, I am not sure what a good test would be. 
- [x] If this is a bugfix, I have provided code that clearly demonstrates the problem and that works when used with this PR
- [ ] I have added a test to the test suite, if necessary
- [ ] I have properly documented new or changed features in the documention, or the docstrings
- [ ] I have properly documented unusual changes to the code in the comments around it
- [ ] I have made note of any breaking/backwards incompatible changes

### CODE REVIEW

**Comment by Overdrivr** [comment]
Hi @TheShadow29, thanks for your contribution. Could you please:

- rebase your branch against master as there as been some changes on this piece of code
- write a new test case for ffmpeg_parse_infos, by simply parsing the faulty video you've mentioned [here](https://github.com/Zulko/moviepy/issues/140)?

Thanks

**Comment by TheShadow29** [comment]
Sure. I will try to do it sometime on the weekend

**Comment by daniestrella1** [comment]
Is this fix added on release 1.0.0?

**Comment by tburrows13** [comment]
Hi, it looks like this section of code was changed in https://github.com/Zulko/moviepy/commit/350571acfe620bf1479fba555d55efb28d51e568 so this PR can be closed as it is no longer relevant. The new fix is in #959 so feel free to try that change out and report back on it.

**Pull request closed without merging**
