### PR TITLE
Apply and ensure Black formatting

### PR DESCRIPTION
**Pull request by mgaitan**
Fix for #1097

### CODE REVIEW

**Comment by tburrows13** [comment]
So am I correct in saying that this doesn't actually auto-format the code, it just marks PRs as unsuccessful (and therefore unmergable) if they fail?

**Comment by mgaitan** [comment]
@tburrows13 yes, you are right.

**Comment by mgaitan** [comment]
well, I don't know why the git action didn't run. It was automatic when I tried this on my fork. 
It seems related to this bug https://github.community/t5/GitHub-Actions/Github-Workflow-not-running-from-pull-request-from-forked/td-p/32979. 

Anyway, should be ok after merge.

**Comment by mgaitan** [comment]
And I'm wondering if wouldn't be better to implement #1081 first, removing old python version from the CI matrixes, and apply this targeting directly py36. So, we don't need another PR to apply a new black rewrite.

**Comment by tburrows13** [comment]
I agree, I intend to start a new branch today for v2.0 that remove all py27 testing. Then we can merge PRs like this one into it.

**Comment by tburrows13** [comment]
A bit later than expected, I've created #1103. When #1103 is merged into the v2 branch, you can update this PR with a fresh run of Black (without worrying about Py2.7, and then we can merge this in before anything else is merged).

I think adding something into the 'Standard workflow' in `Contributing.md` would be helpful as well.

Also I think the name 'sanity checks' is not very descriptive. How about 'Code Format Check' or something like that?

**Comment by mgaitan** [comment]
@tburrows13 update done.

**Comment by tburrows13** [comment]
Thanks for this. I'm happy to merge now.

**Pull request merged**
